const newTestamentEasy = [
  // 1-34: Easy Questions
  {
    id: "nt-easy-1",
    book: "New Testament",
    chapter: "Matthew",
    question: "Who was the mother of Jesus?",
    options: ["Mary", "Elizabeth", "Martha", "Sarah"],
    answer: "Mary",
    level: "easy",
    hint: "Matthew 1:18",
  },
  {
    id: "nt-easy-2",
    book: "New Testament",
    chapter: "Mark",
    question:
      "What is the first miracle Jesus performed according to the Gospel of Mark?",
    options: [
      "Turning water into wine",
      "Healing a paralytic",
      "Calming the storm",
      "Feeding the 5000",
    ],
    answer: "Healing a paralytic",
    level: "easy",
    hint: "Mark 2:1-12",
  },
  {
    id: "nt-easy-3",
    book: "New Testament",
    chapter: "Luke",
    question:
      "Who was the tax collector that climbed a sycamore tree to see Jesus?",
    options: ["Zacchaeus", "Levi", "Matthew", "Simon"],
    answer: "Zacchaeus",
    level: "easy",
    hint: "Luke 19:1-10",
  },
  {
    id: "nt-easy-4",
    book: "New Testament",
    chapter: "John",
    question: "Who denied Jesus three times before the rooster crowed?",
    options: ["Peter", "James", "John", "Andrew"],
    answer: "Peter",
    level: "easy",
    hint: "John 18:15-27",
  },
  {
    id: "nt-easy-5",
    book: "New Testament",
    chapter: "Acts",
    question: "Who was the first Christian martyr?",
    options: ["Stephen", "James", "Paul", "Barnabas"],
    answer: "Stephen",
    level: "easy",
    hint: "Acts 7:54-60",
  },
  {
    id: "nt-easy-6",
    book: "New Testament",
    chapter: "Romans",
    question: "According to Romans, what is the result of sin?",
    options: ["Death", "Salvation", "Peace", "Prosperity"],
    answer: "Death",
    level: "easy",
    hint: "Romans 6:23",
  },
  {
    id: "nt-easy-7",
    book: "New Testament",
    chapter: "1 Corinthians",
    question: "What issue was Paul addressing in 1 Corinthians 13?",
    options: ["Love", "Divisions in the church", "Immorality", "Idolatry"],
    answer: "Love",
    level: "easy",
    hint: "1 Corinthians 13",
  },
  {
    id: "nt-easy-8",
    book: "New Testament",
    chapter: "Galatians",
    question:
      "What fruit of the Spirit does Paul mention first in Galatians 5?",
    options: ["Love", "Joy", "Peace", "Patience"],
    answer: "Love",
    level: "easy",
    hint: "Galatians 5:22-23",
  },
  {
    id: "nt-easy-9",
    book: "New Testament",
    chapter: "Ephesians",
    question: "Who is described as the head of the church in Ephesians?",
    options: ["Jesus Christ", "Paul", "Peter", "James"],
    answer: "Jesus Christ",
    level: "easy",
    hint: "Ephesians 1:22-23",
  },
  {
    id: "nt-easy-10",
    book: "New Testament",
    chapter: "Philippians",
    question:
      "What attitude does Paul encourage believers to have in Philippians 4?",
    options: [
      "Rejoice always",
      "Be anxious",
      "Fight constantly",
      "Seek vengeance",
    ],
    answer: "Rejoice always",
    level: "easy",
    hint: "Philippians 4:4",
  },
  {
    id: "nt-easy-11",
    book: "New Testament",
    chapter: "James",
    question: "What does James say is the mark of a true religion?",
    options: [
      "Care for widows and orphans",
      "Regular church attendance",
      "Financial donations",
      "Personal piety",
    ],
    answer: "Care for widows and orphans",
    level: "easy",
    hint: "James 1:27",
  },
  {
    id: "nt-easy-12",
    book: "New Testament",
    chapter: "1 Peter",
    question:
      "According to 1 Peter, what should believers do when they face suffering?",
    options: [
      "Entrust themselves to God",
      "Seek revenge",
      "Hide from the world",
      "Compete with others",
    ],
    answer: "Entrust themselves to God",
    level: "easy",
    hint: "1 Peter 5:7",
  },
  {
    id: "nt-easy-13",
    book: "New Testament",
    chapter: "Hebrews",
    question: "According to Hebrews, who is the perfect high priest?",
    options: ["Jesus Christ", "Melchizedek", "Aaron", "Moses"],
    answer: "Jesus Christ",
    level: "easy",
    hint: "Hebrews 4:14-16",
  },
  {
    id: "nt-easy-14",
    book: "New Testament",
    chapter: "Revelation",
    question: "What number is associated with the beast in Revelation?",
    options: ["666", "777", "888", "999"],
    answer: "666",
    level: "easy",
    hint: "Revelation 13:18",
  },
  {
    id: "nt-easy-15",
    book: "New Testament",
    chapter: "John",
    question: 'Who was known as the "beloved disciple" in the Gospel of John?',
    options: ["John", "Peter", "James", "Andrew"],
    answer: "John",
    level: "easy",
    hint: "John 13:23",
  },
  {
    id: "nt-easy-16",
    book: "New Testament",
    chapter: "Acts",
    question: "Who was known as the first Gentile convert?",
    options: ["Cornelius", "Paul", "Barnabas", "Silas"],
    answer: "Cornelius",
    level: "easy",
    hint: "Acts 10:1-48",
  },
  {
    id: "nt-easy-17",
    book: "New Testament",
    chapter: "Matthew",
    question:
      "What event marks the beginning of Jesus’ public ministry in Matthew?",
    options: [
      "Baptism by John",
      "The Sermon on the Mount",
      "Walking on water",
      "Feeding the 5000",
    ],
    answer: "Baptism by John",
    level: "easy",
    hint: "Matthew 3:13-17",
  },
  {
    id: "nt-easy-18",
    book: "New Testament",
    chapter: "Mark",
    question:
      "Which disciple is known for his doubt until he sees Jesus’ wounds?",
    options: ["Thomas", "Peter", "John", "James"],
    answer: "Thomas",
    level: "easy",
    hint: "John 20:24-29",
  },
  {
    id: "nt-easy-19",
    book: "New Testament",
    chapter: "Luke",
    question:
      "Who was the prophetess who recognized Jesus as the Messiah in Luke 24?",
    options: ["Anna", "Deborah", "Huldah", "Sarah"],
    answer: "Anna",
    level: "easy",
    hint: "Luke 24:36-43",
  },
  {
    id: "nt-easy-20",
    book: "New Testament",
    chapter: "Acts",
    question: 'Who is known as the "apostle to the Gentiles"?',
    options: ["Paul", "Peter", "James", "John"],
    answer: "Paul",
    level: "easy",
    hint: "Acts 13:47",
  },
  {
    id: "nt-easy-21",
    book: "New Testament",
    chapter: "Romans",
    question: "What is the main theme of the Book of Romans?",
    options: [
      "Justification by faith",
      "Church organization",
      "End times prophecy",
      "Miracles of Jesus",
    ],
    answer: "Justification by faith",
    level: "easy",
    hint: "Romans 1:16-17",
  },
  {
    id: "nt-easy-22",
    book: "New Testament",
    chapter: "1 Corinthians",
    question:
      "In 1 Corinthians 6, what issue does Paul address concerning believers?",
    options: [
      "Lawsuits among believers",
      "Fasting practices",
      "Speaking in tongues",
      "Sacrificial offerings",
    ],
    answer: "Lawsuits among believers",
    level: "easy",
    hint: "1 Corinthians 6:1-8",
  },
  {
    id: "nt-easy-23",
    book: "New Testament",
    chapter: "Galatians",
    question: "What does Paul argue is the true freedom in Galatians?",
    options: [
      "Freedom from the law",
      "Freedom from work",
      "Freedom from sin",
      "Freedom from fear",
    ],
    answer: "Freedom from the law",
    level: "easy",
    hint: "Galatians 5:1",
  },
  {
    id: "nt-easy-24",
    book: "New Testament",
    chapter: "Ephesians",
    question: "According to Ephesians, what has God done for the church?",
    options: [
      "Brought peace through the cross",
      "Given them wealth",
      "Appointed them kings",
      "Granted them immortality",
    ],
    answer: "Brought peace through the cross",
    level: "easy",
    hint: "Ephesians 2:14-18",
  },
  {
    id: "nt-easy-25",
    book: "New Testament",
    chapter: "Philippians",
    question: "What does Paul encourage believers to do in Philippians 2?",
    options: [
      "Have the same mindset as Christ",
      "Seek revenge",
      "Accumulate wealth",
      "Live independently",
    ],
    answer: "Have the same mindset as Christ",
    level: "easy",
    hint: "Philippians 2:5",
  },
  {
    id: "nt-easy-26",
    book: "New Testament",
    chapter: "James",
    question: "According to James 2, what demonstrates faith?",
    options: ["Works", "Prayer", "Fasting", "Singing"],
    answer: "Works",
    level: "easy",
    hint: "James 2:17",
  },
  {
    id: "nt-easy-27",
    book: "New Testament",
    chapter: "1 Peter",
    question: "What is the main message of 1 Peter?",
    options: [
      "Living as strangers and exiles",
      "Accumulating wealth",
      "Political power",
      "Military conquest",
    ],
    answer: "Living as strangers and exiles",
    level: "easy",
    hint: "1 Peter 1:1-2",
  },
  {
    id: "nt-easy-28",
    book: "New Testament",
    chapter: "Hebrews",
    question: "Who is Jesus compared to in the Book of Hebrews?",
    options: ["Melchizedek", "Moses", "Aaron", "Elijah"],
    answer: "Melchizedek",
    level: "easy",
    hint: "Hebrews 7",
  },
  {
    id: "nt-easy-29",
    book: "New Testament",
    chapter: "Revelation",
    question: "Who is the author of the Book of Revelation?",
    options: ["John the Apostle", "Paul", "Peter", "James"],
    answer: "John the Apostle",
    level: "easy",
    hint: "Revelation 1:1",
  },
  {
    id: "nt-easy-30",
    book: "New Testament",
    chapter: "John",
    question: "What is the central theme of the Gospel of John?",
    options: [
      "The divinity of Christ",
      "Miracles of Jesus",
      "Parables",
      "Jesus’ teachings on the Kingdom of God",
    ],
    answer: "The divinity of Christ",
    level: "easy",
    hint: "John 1:1-14",
  },
  {
    id: "nt-easy-31",
    book: "New Testament",
    chapter: "Acts",
    question: "What event marked the birth of the church in Acts 2?",
    options: [
      "Pentecost",
      "The Last Supper",
      "Jesus’ resurrection",
      "Paul’s conversion",
    ],
    answer: "Pentecost",
    level: "easy",
    hint: "Acts 2:1-4",
  },
  {
    id: "nt-easy-32",
    book: "New Testament",
    chapter: "Romans",
    question: "Who wrote the Book of Romans?",
    options: ["Paul", "Peter", "John", "James"],
    answer: "Paul",
    level: "easy",
    hint: "Romans 1:1",
  },
  {
    id: "nt-easy-33",
    book: "New Testament",
    chapter: "1 Corinthians",
    question: "What was the main issue addressed in 1 Corinthians 11?",
    options: [
      "Head coverings and propriety in worship",
      "Fasting",
      "Tithing",
      "Marriage",
    ],
    answer: "Head coverings and propriety in worship",
    level: "easy",
    hint: "1 Corinthians 11:2-16",
  },
  {
    id: "nt-easy-34",
    book: "New Testament",
    chapter: "Galatians",
    question: "Who was Paul’s missionary companion mentioned in Galatians?",
    options: ["Barnabas", "Silas", "Timothy", "Luke"],
    answer: "Barnabas",
    level: "easy",
    hint: "Galatians 2:1-10",
  },
];

const newTestamentMedium = [
  // 1-34: Medium Questions
  {
    id: "nt-medium-1",
    book: "New Testament",
    chapter: "Matthew",
    question: 'What is the Beatitude that begins with "Blessed are the meek"?',
    options: ["Matthew 5:5", "Matthew 5:3", "Matthew 5:6", "Matthew 5:4"],
    answer: "Matthew 5:5",
    level: "medium",
    hint: "Matthew 5:5",
  },
  {
    id: "nt-medium-2",
    book: "New Testament",
    chapter: "Mark",
    question:
      "In the Gospel of Mark, who is the first person to recognize Jesus after His resurrection?",
    options: ["Mary Magdalene", "Peter", "John", "Thomas"],
    answer: "Mary Magdalene",
    level: "medium",
    hint: "Mark 16:9",
  },
  {
    id: "nt-medium-3",
    book: "New Testament",
    chapter: "Luke",
    question: "What is the significance of the Good Samaritan parable in Luke?",
    options: [
      "Illustrates who is a neighbor",
      "Teaches about prayer",
      "Explains the Kingdom of God",
      "Describes the end times",
    ],
    answer: "Illustrates who is a neighbor",
    level: "medium",
    hint: "Luke 10:25-37",
  },
  {
    id: "nt-medium-4",
    book: "New Testament",
    chapter: "John",
    question:
      "In the Gospel of John, what does Jesus say about Himself in John 14:6?",
    options: [
      '"I am the way, the truth, and the life. No one comes to the Father except through me."',
      '"I am the bread of life."',
      '"I am the light of the world."',
      '"I am the good shepherd."',
    ],
    answer:
      '"I am the way, the truth, and the life. No one comes to the Father except through me."',
    level: "medium",
    hint: "John 14:6",
  },
  {
    id: "nt-medium-5",
    book: "New Testament",
    chapter: "Acts",
    question:
      "What significant event occurred on the day of Pentecost in Acts?",
    options: [
      "The Holy Spirit descended on the apostles",
      "The resurrection of Jesus",
      "Paul’s conversion",
      "The building of the first church",
    ],
    answer: "The Holy Spirit descended on the apostles",
    level: "medium",
    hint: "Acts 2:1-4",
  },
  {
    id: "nt-medium-6",
    book: "New Testament",
    chapter: "Romans",
    question:
      "What does Paul describe as “the power of God for salvation” in Romans 1:16?",
    options: ["The Gospel of Christ", "Faith", "Love", "Grace"],
    answer: "The Gospel of Christ",
    level: "medium",
    hint: "Romans 1:16",
  },
  {
    id: "nt-medium-7",
    book: "New Testament",
    chapter: "1 Corinthians",
    question:
      'In 1 Corinthians 15, what does Paul say is the "firstfruits of those who have fallen asleep"?',
    options: ["Christ", "Believers", "Angels", "Prophets"],
    answer: "Christ",
    level: "medium",
    hint: "1 Corinthians 15:20",
  },
  {
    id: "nt-medium-8",
    book: "New Testament",
    chapter: "Galatians",
    question: "What argument does Paul make against circumcision in Galatians?",
    options: [
      "It is not necessary for salvation",
      "It is required for Gentiles",
      "It is a punishment",
      "It is a sign of weakness",
    ],
    answer: "It is not necessary for salvation",
    level: "medium",
    hint: "Galatians 5:6",
  },
  {
    id: "nt-medium-9",
    book: "New Testament",
    chapter: "Ephesians",
    question: "According to Ephesians, what is the church described as?",
    options: [
      "The body of Christ",
      "A kingdom",
      "A school",
      "A military force",
    ],
    answer: "The body of Christ",
    level: "medium",
    hint: "Ephesians 1:22-23",
  },
  {
    id: "nt-medium-10",
    book: "New Testament",
    chapter: "Philippians",
    question:
      "In Philippians 4, what does Paul encourage believers to do with anxiety?",
    options: [
      "Pray about everything",
      "Ignore it",
      "Worry constantly",
      "Compete with others",
    ],
    answer: "Pray about everything",
    level: "medium",
    hint: "Philippians 4:6",
  },
  {
    id: "nt-medium-11",
    book: "New Testament",
    chapter: "James",
    question: "According to James 1:22, what should believers do?",
    options: [
      "Do what the word says",
      "Listen passively",
      "Attend church regularly",
      "Give generously",
    ],
    answer: "Do what the word says",
    level: "medium",
    hint: "James 1:22",
  },
  {
    id: "nt-medium-12",
    book: "New Testament",
    chapter: "1 Peter",
    question:
      "In 1 Peter 2, what metaphor does Peter use to describe believers?",
    options: [
      "Living stones",
      "Branches of a tree",
      "Stars in the sky",
      "Seeds in the soil",
    ],
    answer: "Living stones",
    level: "medium",
    hint: "1 Peter 2:5",
  },
  {
    id: "nt-medium-13",
    book: "New Testament",
    chapter: "Hebrews",
    question: "What does Hebrews 11 focus on?",
    options: ["Faith", "Law", "Sacrifice", "Church organization"],
    answer: "Faith",
    level: "medium",
    hint: "Hebrews 11",
  },
  {
    id: "nt-medium-14",
    book: "New Testament",
    chapter: "Revelation",
    question: "What is the primary theme of the Book of Revelation?",
    options: [
      "End times and the return of Jesus",
      "The life of Jesus",
      "Paul’s missionary journeys",
      "Church organization",
    ],
    answer: "End times and the return of Jesus",
    level: "medium",
    hint: "Revelation 1:1",
  },
  {
    id: "nt-medium-15",
    book: "New Testament",
    chapter: "John",
    question: "In John 3, who does Jesus speak with at night?",
    options: ["Nicodemus", "Peter", "John", "Thomas"],
    answer: "Nicodemus",
    level: "medium",
    hint: "John 3:1-21",
  },
  {
    id: "nt-medium-16",
    book: "New Testament",
    chapter: "Acts",
    question:
      "Who succeeded Peter as the leader of the church after his martyrdom?",
    options: ["James", "John", "Barnabas", "Paul"],
    answer: "James",
    level: "medium",
    hint: "Acts 12:17",
  },
  {
    id: "nt-medium-17",
    book: "New Testament",
    chapter: "Romans",
    question:
      "What analogy does Paul use in Romans 8 to describe the believers’ life?",
    options: [
      "They are heirs of God",
      "They are aliens in a foreign land",
      "They are soldiers in a spiritual battle",
      "They are like sheep following a shepherd",
    ],
    answer: "They are soldiers in a spiritual battle",
    level: "medium",
    hint: "Romans 8:35-39",
  },
  {
    id: "nt-medium-18",
    book: "New Testament",
    chapter: "1 Corinthians",
    question:
      "In 1 Corinthians 12, what metaphor does Paul use to describe the church?",
    options: [
      "A body with many parts",
      "A building with many bricks",
      "A garden with many flowers",
      "A ship with many sails",
    ],
    answer: "A body with many parts",
    level: "medium",
    hint: "1 Corinthians 12:12-27",
  },
  {
    id: "nt-medium-19",
    book: "New Testament",
    chapter: "Galatians",
    question:
      "What does Paul say is the only thing that counts in Galatians 5:6?",
    options: [
      "Faith expressing itself through love",
      "Circumcision",
      "Observing the Sabbath",
      "Offering sacrifices",
    ],
    answer: "Faith expressing itself through love",
    level: "medium",
    hint: "Galatians 5:6",
  },
  {
    id: "nt-medium-20",
    book: "New Testament",
    chapter: "Ephesians",
    question: "What does Paul describe in Ephesians 6 as the “belt of truth”?",
    options: [
      "A metaphor for honesty and integrity",
      "A physical belt for soldiers",
      "A symbol of leadership",
      "A gift to the church",
    ],
    answer: "A metaphor for honesty and integrity",
    level: "medium",
    hint: "Ephesians 6:14",
  },
  {
    id: "nt-medium-21",
    book: "New Testament",
    chapter: "Philippians",
    question: "In Philippians 4, what does Paul say about anxiety?",
    options: [
      "Do not be anxious about anything",
      "Be anxious always",
      "Let anxiety consume you",
      "Avoid prayer",
    ],
    answer: "Do not be anxious about anything",
    level: "medium",
    hint: "Philippians 4:6",
  },
  {
    id: "nt-medium-22",
    book: "New Testament",
    chapter: "James",
    question: "According to James 2, what completes faith?",
    options: ["Works", "Prayer", "Fasting", "Singing"],
    answer: "Works",
    level: "medium",
    hint: "James 2:17",
  },
  {
    id: "nt-medium-23",
    book: "New Testament",
    chapter: "1 Peter",
    question:
      "In 1 Peter 3, how are wives instructed to behave towards their husbands?",
    options: [
      "With respect and quietness",
      "With rebellion",
      "With fear",
      "With anger",
    ],
    answer: "With respect and quietness",
    level: "medium",
    hint: "1 Peter 3:1-6",
  },
  {
    id: "nt-medium-24",
    book: "New Testament",
    chapter: "Hebrews",
    question: "What does Hebrews 10:19-22 encourage believers to do?",
    options: [
      "Approach God with a sincere heart",
      "Retreat from the world",
      "Seek revenge",
      "Compete with others",
    ],
    answer: "Approach God with a sincere heart",
    level: "medium",
    hint: "Hebrews 10:19-22",
  },
  {
    id: "nt-medium-25",
    book: "New Testament",
    chapter: "Revelation",
    question: "What is the primary message conveyed in Revelation 1?",
    options: [
      "The revelation of Jesus Christ",
      "The history of the church",
      "The life of John",
      "The creation story",
    ],
    answer: "The revelation of Jesus Christ",
    level: "medium",
    hint: "Revelation 1:1",
  },
  {
    id: "nt-medium-26",
    book: "New Testament",
    chapter: "John",
    question: "In John 8, what does Jesus declare Himself as?",
    options: [
      "The Light of the World",
      "The Bread of Life",
      "The Good Shepherd",
      "The Alpha and Omega",
    ],
    answer: "The Light of the World",
    level: "medium",
    hint: "John 8:12",
  },
  {
    id: "nt-medium-27",
    book: "New Testament",
    chapter: "Acts",
    question: "Who replaced Judas Iscariot as an apostle in Acts 1?",
    options: ["Matthias", "Bartholomew", "Simon", "Thaddaeus"],
    answer: "Matthias",
    level: "medium",
    hint: "Acts 1:23-26",
  },
  {
    id: "nt-medium-28",
    book: "New Testament",
    chapter: "Romans",
    question: "In Romans 8, what assurance does Paul give believers?",
    options: [
      "Nothing can separate them from the love of God",
      "They must work harder",
      "They are doomed to fail",
      "They need to earn salvation",
    ],
    answer: "Nothing can separate them from the love of God",
    level: "medium",
    hint: "Romans 8:38-39",
  },
  {
    id: "nt-medium-29",
    book: "New Testament",
    chapter: "1 Corinthians",
    question:
      "In 1 Corinthians 12, what does Paul say about the church being a body?",
    options: [
      "Each member has a unique part to play",
      "All members are identical",
      "Only leaders are important",
      "Members should compete for roles",
    ],
    answer: "Each member has a unique part to play",
    level: "medium",
    hint: "1 Corinthians 12:12-27",
  },
  {
    id: "nt-medium-30",
    book: "New Testament",
    chapter: "Galatians",
    question: "What does Galatians 5:22-23 list?",
    options: [
      "The fruit of the Spirit",
      "The works of the flesh",
      "The ten commandments",
      "The miracles of Jesus",
    ],
    answer: "The fruit of the Spirit",
    level: "medium",
    hint: "Galatians 5:22-23",
  },
  {
    id: "nt-medium-31",
    book: "New Testament",
    chapter: "Ephesians",
    question:
      "According to Ephesians 4, what should believers strive for in unity?",
    options: [
      "The same mind and the same faith",
      "Different opinions",
      "Isolation",
      "Dominance",
    ],
    answer: "The same mind and the same faith",
    level: "medium",
    hint: "Ephesians 4:4-6",
  },
  {
    id: "nt-medium-32",
    book: "New Testament",
    chapter: "Philippians",
    question: "In Philippians 2, what example does Paul give of humility?",
    options: [
      "Jesus, who took on the form of a servant",
      "Peter, who led the church",
      "Paul, who was a prisoner",
      "Barnabas, who encouraged others",
    ],
    answer: "Jesus, who took on the form of a servant",
    level: "medium",
    hint: "Philippians 2:5-8",
  },
  {
    id: "nt-medium-33",
    book: "New Testament",
    chapter: "James",
    question: "According to James 2:14-17, what is useless?",
    options: [
      "Faith without works",
      "Prayer without belief",
      "Fasting without joy",
      "Singing without understanding",
    ],
    answer: "Faith without works",
    level: "medium",
    hint: "James 2:14-17",
  },
  {
    id: "nt-medium-34",
    book: "New Testament",
    chapter: "1 Peter",
    question:
      "In 1 Peter 4, what does Peter say believers should do with their time?",
    options: [
      "Be self-controlled and sober-minded",
      "Waste it on pleasures",
      "Fight against sin",
      "Accumulate wealth",
    ],
    answer: "Be self-controlled and sober-minded",
    level: "medium",
    hint: "1 Peter 4:7",
  },
];

const newTestamentHard = [
  // 1-34: Hard Questions
  {
    id: "nt-hard-1",
    book: "New Testament",
    chapter: "Romans",
    question:
      "In Romans 8, Paul discusses life in the Spirit. What does he say believers are no longer under?",
    options: [
      "The law of sin and death",
      "Governments",
      "Pagan gods",
      "Evil spirits",
    ],
    answer: "The law of sin and death",
    level: "hard",
    hint: "Romans 8:2",
  },
  {
    id: "nt-hard-2",
    book: "New Testament",
    chapter: "1 Corinthians",
    question:
      "In 1 Corinthians 11, what practice does Paul address concerning women during worship?",
    options: ["Head coverings", "Fasting", "Prayer", "Singing"],
    answer: "Head coverings",
    level: "hard",
    hint: "1 Corinthians 11:4-16",
  },
  {
    id: "nt-hard-3",
    book: "New Testament",
    chapter: "Galatians",
    question:
      "What metaphor does Paul use in Galatians 5 to describe the conflict between the flesh and the Spirit?",
    options: [
      "The war between two armies",
      "A wrestling match",
      "A battle between a lion and a lamb",
      "A race",
    ],
    answer: "The war between two armies",
    level: "hard",
    hint: "Galatians 5:17",
  },
  {
    id: "nt-hard-4",
    book: "New Testament",
    chapter: "Ephesians",
    question: 'What does Paul refer to in Ephesians 6 as the "armor of God"?',
    options: [
      "Spiritual virtues and defenses",
      "Physical armor for soldiers",
      "Church leadership",
      "Sacrificial offerings",
    ],
    answer: "Spiritual virtues and defenses",
    level: "hard",
    hint: "Ephesians 6:10-18",
  },
  {
    id: "nt-hard-5",
    book: "New Testament",
    chapter: "Philippians",
    question:
      "In Philippians 3, Paul talks about his former life. What does he consider as loss compared to knowing Christ?",
    options: ["All his gains", "His family", "His wealth", "His reputation"],
    answer: "All his gains",
    level: "hard",
    hint: "Philippians 3:7-8",
  },
  {
    id: "nt-hard-6",
    book: "New Testament",
    chapter: "James",
    question: "What does James equate faith without works to in James 2?",
    options: [
      "Dead faith",
      "Strong faith",
      "Confused faith",
      "Delighted faith",
    ],
    answer: "Dead faith",
    level: "hard",
    hint: "James 2:17",
  },
  {
    id: "nt-hard-7",
    book: "New Testament",
    chapter: "1 Peter",
    question:
      "According to 1 Peter 3, how should wives respond to their husbands?",
    options: [
      "With respect and quietness",
      "With rebellion",
      "With fear",
      "With anger",
    ],
    answer: "With respect and quietness",
    level: "hard",
    hint: "1 Peter 3:1-6",
  },
  {
    id: "nt-hard-8",
    book: "New Testament",
    chapter: "Hebrews",
    question:
      "What does Hebrews 7:23-25 emphasize about Jesus’ priesthood compared to Melchizedek’s?",
    options: [
      "Jesus’ priesthood is eternal and perfected",
      "Jesus’ priesthood is temporary",
      "Jesus served under Melchizedek",
      "Melchizedek was superior",
    ],
    answer: "Jesus’ priesthood is eternal and perfected",
    level: "hard",
    hint: "Hebrews 7:23-25",
  },
  {
    id: "nt-hard-9",
    book: "New Testament",
    chapter: "Revelation",
    question: 'In Revelation, what does the "New Jerusalem" symbolize?',
    options: [
      "The eternal dwelling of the redeemed with God",
      "A future earthly city",
      "A metaphor for the church",
      "The Holy Spirit",
    ],
    answer: "The eternal dwelling of the redeemed with God",
    level: "hard",
    hint: "Revelation 21:2-27",
  },
  {
    id: "nt-hard-10",
    book: "New Testament",
    chapter: "John",
    question: "In John 17, what is the primary focus of Jesus’ prayer?",
    options: [
      "The unity and protection of his followers",
      "His own well-being",
      "The prosperity of Israel",
      "The judgment of the wicked",
    ],
    answer: "The unity and protection of his followers",
    level: "hard",
    hint: "John 17",
  },
  {
    id: "nt-hard-11",
    book: "New Testament",
    chapter: "Acts",
    question:
      "What role did Barnabas play in the early church according to Acts?",
    options: [
      "Encourager and missionary partner of Paul",
      "Leader of the Jerusalem church",
      "Head of the apostles",
      "Guardian of the Holy Spirit",
    ],
    answer: "Encourager and missionary partner of Paul",
    level: "hard",
    hint: "Acts 4:36-37; Acts 13:2-3",
  },
  {
    id: "nt-hard-12",
    book: "New Testament",
    chapter: "Romans",
    question:
      "In Romans 9-11, Paul discusses the relationship between Israel and Gentiles. What is his main argument?",
    options: [
      "God has not rejected Israel and there is a future for them in salvation",
      "Israel is completely rejected by God",
      "Gentiles have no place in God’s plan",
      "Salvation is only for Jews",
    ],
    answer:
      "God has not rejected Israel and there is a future for them in salvation",
    level: "hard",
    hint: "Romans 11:1-36",
  },
  {
    id: "nt-hard-13",
    book: "New Testament",
    chapter: "1 Corinthians",
    question:
      'In 1 Corinthians 15, what does Paul describe as "the firstfruits of those who have fallen asleep"?',
    options: ["Christ", "Believers", "Angels", "Prophets"],
    answer: "Christ",
    level: "hard",
    hint: "1 Corinthians 15:20",
  },
  {
    id: "nt-hard-14",
    book: "New Testament",
    chapter: "Galatians",
    question:
      'What is the "Galatian dilemma" that Paul addresses in his letter?',
    options: [
      "Faith vs. works of the law",
      "Marital issues",
      "Church divisions",
      "Elder qualifications",
    ],
    answer: "Faith vs. works of the law",
    level: "hard",
    hint: "Galatians 2:16-21",
  },
  {
    id: "nt-hard-15",
    book: "New Testament",
    chapter: "Ephesians",
    question: "According to Ephesians 2, how were believers made alive?",
    options: [
      "By grace through faith in Christ",
      "By their own efforts",
      "Through good works",
      "By observing the law",
    ],
    answer: "By grace through faith in Christ",
    level: "hard",
    hint: "Ephesians 2:4-5",
  },
  {
    id: "nt-hard-16",
    book: "New Testament",
    chapter: "Philippians",
    question: "What does Paul say about his own achievements in Philippians 3?",
    options: [
      "He considers them loss compared to knowing Christ",
      "He boasts about them",
      "He ignores them",
      "He regrets them",
    ],
    answer: "He considers them loss compared to knowing Christ",
    level: "hard",
    hint: "Philippians 3:7-8",
  },
  {
    id: "nt-hard-17",
    book: "New Testament",
    chapter: "James",
    question:
      "What analogy does James use to describe faith without works in James 2?",
    options: [
      "A body without the spirit is dead",
      "A tree without fruit is barren",
      "A lamp without oil does not shine",
      "A ship without sails is stranded",
    ],
    answer: "A body without the spirit is dead",
    level: "hard",
    hint: "James 2:26",
  },
  {
    id: "nt-hard-18",
    book: "New Testament",
    chapter: "1 Peter",
    question: "In 1 Peter 2, what is believers’ role in the world?",
    options: [
      "Living as obedient children",
      "Dominating others",
      "Isolating themselves",
      "Accumulating wealth",
    ],
    answer: "Living as obedient children",
    level: "hard",
    hint: "1 Peter 2:12",
  },
  {
    id: "nt-hard-19",
    book: "New Testament",
    chapter: "Hebrews",
    question: "What does Hebrews 10:19-22 encourage believers to do?",
    options: [
      "Approach God with a sincere heart",
      "Retreat from the world",
      "Seek revenge",
      "Compete with others",
    ],
    answer: "Approach God with a sincere heart",
    level: "hard",
    hint: "Hebrews 10:19-22",
  },
  {
    id: "nt-hard-20",
    book: "New Testament",
    chapter: "Revelation",
    question:
      "In Revelation 21, what is the name of the river that flows from the throne of God?",
    options: ["River of Life", "Jordan River", "Euphrates", "Nile"],
    answer: "River of Life",
    level: "hard",
    hint: "Revelation 22:1",
  },
  {
    id: "nt-hard-21",
    book: "New Testament",
    chapter: "Matthew",
    question: "In the Sermon on the Mount, what does Jesus say about salt?",
    options: [
      "It should be pure",
      "It should be sacrificed",
      "It should be shared with the poor",
      "It should be used for offerings",
    ],
    answer: "It should be pure",
    level: "hard",
    hint: "Matthew 5:13",
  },
  {
    id: "nt-hard-22",
    book: "New Testament",
    chapter: "Mark",
    question:
      "What was the reaction of the crowd when Jesus calmed the storm in Mark 4?",
    options: [
      "They were amazed and questioned His authority",
      "They were fearful and fled",
      "They ignored the miracle",
      "They worshipped Him immediately",
    ],
    answer: "They were amazed and questioned His authority",
    level: "hard",
    hint: "Mark 4:35-41",
  },
  {
    id: "nt-hard-23",
    book: "New Testament",
    chapter: "Luke",
    question:
      "In the Parable of the Good Samaritan, who is considered the neighbor?",
    options: [
      "A Samaritan who helps the injured man",
      "A priest",
      "A Levite",
      "A tax collector",
    ],
    answer: "A Samaritan who helps the injured man",
    level: "hard",
    hint: "Luke 10:25-37",
  },
  {
    id: "nt-hard-24",
    book: "New Testament",
    chapter: "John",
    question:
      "What theological concept is central to the Gospel of John, especially in John 1?",
    options: [
      "The Logos (Word) was with God and was God",
      "The Law was given by Moses",
      "Jesus was a prophet like Elijah",
      "Salvation is achieved through works",
    ],
    answer: "The Logos (Word) was with God and was God",
    level: "hard",
    hint: "John 1:1-14",
  },
  {
    id: "nt-hard-25",
    book: "New Testament",
    chapter: "Acts",
    question:
      "In Acts 15, what major issue was addressed at the Council of Jerusalem?",
    options: [
      "Whether Gentile believers needed to follow the Mosaic Law",
      "The selection of church leaders",
      "The distribution of church funds",
      "The construction of new churches",
    ],
    answer: "Whether Gentile believers needed to follow the Mosaic Law",
    level: "hard",
    hint: "Acts 15:1-29",
  },
  {
    id: "nt-hard-26",
    book: "New Testament",
    chapter: "Romans",
    question:
      'What does Paul mean by "the wrath of God is being revealed from heaven against all the godlessness and wickedness of people" in Romans 1:18?',
    options: [
      "God is justly punishing sin",
      "God is indifferent to sin",
      "God loves all people unconditionally",
      "God is forgiving without judgment",
    ],
    answer: "God is justly punishing sin",
    level: "hard",
    hint: "Romans 1:18",
  },
  {
    id: "nt-hard-27",
    book: "New Testament",
    chapter: "1 Corinthians",
    question:
      "In 1 Corinthians 14, what does Paul emphasize about speaking in tongues?",
    options: [
      "It should be done in an orderly manner with interpretation",
      "It is the highest gift",
      "It should be done without interpretation",
      "It is unnecessary in the church",
    ],
    answer: "It should be done in an orderly manner with interpretation",
    level: "hard",
    hint: "1 Corinthians 14:27-28",
  },
  {
    id: "nt-hard-28",
    book: "New Testament",
    chapter: "Galatians",
    question: "In Galatians 3, how does Paul describe the purpose of the law?",
    options: [
      "To act as a guardian until Christ came",
      "To provide salvation",
      "To replace faith",
      "To grant eternal life",
    ],
    answer: "To act as a guardian until Christ came",
    level: "hard",
    hint: "Galatians 3:24",
  },
  {
    id: "nt-hard-29",
    book: "New Testament",
    chapter: "Ephesians",
    question: 'What is the "mystery" Paul refers to in Ephesians 3:6?',
    options: [
      "The inclusion of Gentiles in the promise of Christ",
      "The resurrection of the dead",
      "The second coming of Christ",
      "The nature of the Trinity",
    ],
    answer: "The inclusion of Gentiles in the promise of Christ",
    level: "hard",
    hint: "Ephesians 3:6",
  },
  {
    id: "nt-hard-30",
    book: "New Testament",
    chapter: "Philippians",
    question: "In Philippians 2, how does Paul describe Jesus’ humility?",
    options: [
      [
        "He took on the nature of a servant and became obedient to death",
        "He became a powerful king",
        "He amassed great wealth",
        "He ignored the needs of others",
      ],
      [
        "He took on the nature of a servant and became obedient to death",
        "He became a powerful king",
        "He amassed great wealth",
        "He ignored the needs of others",
      ],
    ],
    answer: "He took on the nature of a servant and became obedient to death",
    level: "hard",
    hint: "Philippians 2:6-8",
  },
  {
    id: "nt-hard-31",
    book: "New Testament",
    chapter: "James",
    question: "What does James say about listening and doing in James 1:22?",
    options: [
      [
        "Be doers of the word, and not hearers only",
        "Listen only and not act",
        "Ignore the word",
        "Question the word",
      ],
      [
        "Be doers of the word, and not hearers only",
        "Listen only and not act",
        "Ignore the word",
        "Question the word",
      ],
    ],
    answer: "Be doers of the word, and not hearers only",
    level: "hard",
    hint: "James 1:22",
  },
  {
    id: "nt-hard-32",
    book: "New Testament",
    chapter: "1 Peter",
    question:
      "In 1 Peter 4, what does Peter say believers should not be ashamed of?",
    options: [
      [
        "Suffering for doing good",
        "Their wealth",
        "Their status",
        "Their education",
      ],
      [
        "Suffering for doing good",
        "Their wealth",
        "Their status",
        "Their education",
      ],
    ],
    answer: "Suffering for doing good",
    level: "hard",
    hint: "1 Peter 4:16",
  },
  {
    id: "nt-hard-33",
    book: "New Testament",
    chapter: "Hebrews",
    question:
      "According to Hebrews 10:19-22, what can believers approach God with?",
    options: [
      [
        "Confidence and a sincere heart",
        "Fear and trembling",
        "Indifference",
        "Anger",
      ],
      [
        "Confidence and a sincere heart",
        "Fear and trembling",
        "Indifference",
        "Anger",
      ],
    ],
    answer: "Confidence and a sincere heart",
    level: "hard",
    hint: "Hebrews 10:19-22",
  },
  {
    id: "nt-hard-34",
    book: "New Testament",
    chapter: "Revelation",
    question: "In Revelation 20, how long is Satan bound in the Abyss?",
    options: [
      ["A thousand years", "Seven years", "Seventy weeks", "Forever"],
      ["A thousand years", "Seven years", "Seventy weeks", "Forever"],
    ],
    answer: "A thousand years",
    level: "hard",
    hint: "Revelation 20:1-3",
  },
  {
    id: "nt-hard-35",
    book: "New Testament",
    chapter: "Matthew",
    question:
      "In Matthew 26, what significant event takes place during the Last Supper?",
    options: [
      "Jesus institutes the Lord’s Supper",
      "Jesus is baptized",
      "Jesus performs a miracle",
      "Jesus heals a blind man",
    ],
    answer: "Jesus institutes the Lord’s Supper",
    level: "hard",
    hint: "Matthew 26:26-29",
  },
  {
    id: "nt-hard-36",
    book: "New Testament",
    chapter: "Mark",
    question:
      "What is the significance of the “little children” passage in Mark 10?",
    options: [
      "Jesus emphasizes humility and receiving the kingdom like a child",
      "Jesus blesses the children to make them powerful",
      "Jesus dismisses the children from the crowd",
      "Jesus teaches children to read scriptures",
    ],
    answer: "Jesus emphasizes humility and receiving the kingdom like a child",
    level: "hard",
    hint: "Mark 10:13-16",
  },
  {
    id: "nt-hard-37",
    book: "New Testament",
    chapter: "Luke",
    question:
      "In Luke 24, how do the disciples recognize Jesus after His resurrection?",
    options: [
      [
        "By breaking bread with Him",
        "By His voice",
        "By His appearance alone",
        "By a dove descending upon Him",
      ],
      [
        "By breaking bread with Him",
        "By His voice",
        "By His appearance alone",
        "By a dove descending upon Him",
      ],
    ],
    answer: "By breaking bread with Him",
    level: "hard",
    hint: "Luke 24:30-31",
  },
  {
    id: "nt-hard-38",
    book: "New Testament",
    chapter: "John",
    question: 'What does John describe as the "light" in John 8:12?',
    options: [
      ["Jesus", "The Holy Spirit", "The Law", "Faith"],
      ["Jesus", "The Holy Spirit", "The Law", "Faith"],
    ],
    answer: "Jesus",
    level: "hard",
    hint: "John 8:12",
  },
  {
    id: "nt-hard-39",
    book: "New Testament",
    chapter: "Acts",
    question:
      "In Acts 2, what significant event occurs on the day of Pentecost?",
    options: [
      [
        "The coming of the Holy Spirit and speaking in tongues",
        "The selection of the first deacons",
        "The baptism of the Ethiopian eunuch",
        "The conversion of Saul",
      ],
      [
        "The coming of the Holy Spirit and speaking in tongues",
        "The selection of the first deacons",
        "The baptism of the Ethiopian eunuch",
        "The conversion of Saul",
      ],
    ],
    answer: "The coming of the Holy Spirit and speaking in tongues",
    level: "hard",
    hint: "Acts 2:1-4",
  },
  {
    id: "nt-hard-40",
    book: "New Testament",
    chapter: "Romans",
    question:
      "What does Paul argue is the only way to be justified before God in Romans 3?",
    options: [
      [
        "By faith apart from the works of the law",
        "By following the Mosaic Law",
        "By performing good works",
        "By circumcision",
      ],
      [
        "By faith apart from the works of the law",
        "By following the Mosaic Law",
        "By performing good works",
        "By circumcision",
      ],
    ],
    answer: "By faith apart from the works of the law",
    level: "hard",
    hint: "Romans 3:28",
  },
  {
    id: "nt-hard-41",
    book: "New Testament",
    chapter: "1 Corinthians",
    question:
      "In 1 Corinthians 9, what rights does Paul say he has as an apostle?",
    options: [
      [
        "To receive material support",
        "To demand respect",
        "To enforce discipline",
        "To lead the church",
      ],
      [
        "To receive material support",
        "To demand respect",
        "To enforce discipline",
        "To lead the church",
      ],
    ],
    answer: "To receive material support",
    level: "hard",
    hint: "1 Corinthians 9:14",
  },
  {
    id: "nt-hard-42",
    book: "New Testament",
    chapter: "Galatians",
    question:
      "What analogy does Paul use in Galatians 4 to describe believers in Christ?",
    options: [
      [
        "Heirs as sons through God",
        "Shepherds of the flock",
        "Builders of the church",
        "Light in the world",
      ],
      [
        "Heirs as sons through God",
        "Shepherds of the flock",
        "Builders of the church",
        "Light in the world",
      ],
    ],
    answer: "Heirs as sons through God",
    level: "hard",
    hint: "Galatians 4:7",
  },
  {
    id: "nt-hard-43",
    book: "New Testament",
    chapter: "Ephesians",
    question:
      "In Ephesians 1, Paul speaks about believers being chosen in Christ before the foundation of the world. What theological concept does this refer to?",
    options: [
      ["Predestination", "Free will", "Universal salvation", "Reincarnation"],
      ["Predestination", "Free will", "Universal salvation", "Reincarnation"],
    ],
    answer: "Predestination",
    level: "hard",
    hint: "Ephesians 1:4",
  },
  {
    id: "nt-hard-44",
    book: "New Testament",
    chapter: "Philippians",
    question:
      "In Philippians 1:6, what does Paul express confidence about concerning God?",
    options: [
      [
        "That He who began a good work in believers will carry it on to completion",
        "That He will grant all desires",
        "That He will never let believers face hardship",
        "That He will grant eternal life immediately",
      ],
      [
        "That He who began a good work in believers will carry it on to completion",
        "That He will grant all desires",
        "That He will never let believers face hardship",
        "That He will grant eternal life immediately",
      ],
    ],
    answer:
      "That He who began a good work in believers will carry it on to completion",
    level: "hard",
    hint: "Philippians 1:6",
  },
  {
    id: "nt-hard-45",
    book: "New Testament",
    chapter: "James",
    question:
      "In James 1:22, what does James urge believers to do with the word of God?",
    options: [
      [
        "Be doers of the word, and not hearers only",
        "Hear the word and do nothing",
        "Ignore the word",
        "Question the word",
      ],
      [
        "Be doers of the word, and not hearers only",
        "Hear the word and do nothing",
        "Ignore the word",
        "Question the word",
      ],
    ],
    answer: "Be doers of the word, and not hearers only",
    level: "hard",
    hint: "James 1:22",
  },
  {
    id: "nt-hard-46",
    book: "New Testament",
    chapter: "1 Peter",
    question:
      "In 1 Peter 4:12, what does Peter warn believers not to be surprised by?",
    options: [
      [
        "The fiery ordeal that comes on the way",
        "Blessings and prosperity",
        "Eternal life",
        "Miraculous healings",
      ],
      [
        "The fiery ordeal that comes on the way",
        "Blessings and prosperity",
        "Eternal life",
        "Miraculous healings",
      ],
    ],
    answer: "The fiery ordeal that comes on the way",
    level: "hard",
    hint: "1 Peter 4:12",
  },
  {
    id: "nt-hard-47",
    book: "New Testament",
    chapter: "Hebrews",
    question:
      "According to Hebrews 10:19-22, what have believers been given access to by the blood of Jesus?",
    options: [
      [
        "A confident approach to the throne of grace",
        "Unlimited prosperity",
        "Exemption from all laws",
        "Immediate resurrection",
      ],
    ],
    answer: "A confident approach to the throne of grace",
    level: "hard",
    hint: "Hebrews 10:19-22",
  },
  {
    id: "nt-hard-48",
    book: "New Testament",
    chapter: "Revelation",
    question: "In Revelation 20, who binds Satan for a thousand years?",
    options: [
      ["An angel", "Michael", "Jesus Christ", "John"],
      ["An angel", "Michael", "Jesus Christ", "John"],
    ],
    answer: "An angel",
    level: "hard",
    hint: "Revelation 20:1-3",
  },
  {
    id: "nt-hard-49",
    book: "New Testament",
    chapter: "Matthew",
    question:
      "In Matthew 5:44, whom does Jesus instruct His followers to love and pray for?",
    options: [
      [
        "Their enemies",
        "Only their friends",
        "Only their family",
        "Only the righteous",
      ],
      [
        "Their enemies",
        "Only their friends",
        "Only their family",
        "Only the righteous",
      ],
    ],
    answer: "Their enemies",
    level: "hard",
    hint: "Matthew 5:44",
  },
  {
    id: "nt-hard-50",
    book: "New Testament",
    chapter: "Mark",
    question:
      "In Mark 12, what question does Jesus ask to demonstrate His authority?",
    options: [
      [
        "Whose image is this?",
        "What is the kingdom of God?",
        "Who is the greatest in the kingdom?",
        "What is the first commandment?",
      ],
      [
        "Whose image is this?",
        "What is the kingdom of God?",
        "Who is the greatest in the kingdom?",
        "What is the first commandment?",
      ],
    ],
    answer: "Whose image is this?",
    level: "hard",
    hint: "Mark 12:13-17",
  },
  {
    id: "nt-hard-51",
    book: "New Testament",
    chapter: "Luke",
    question:
      "In Luke 10, what parable does Jesus tell about a man beaten by robbers?",
    options: [
      [
        "The Parable of the Good Samaritan",
        "The Parable of the Lost Sheep",
        "The Parable of the Sower",
        "The Parable of the Prodigal Son",
      ],
    ],
    answer: "The Parable of the Good Samaritan",
    level: "hard",
    hint: "Luke 10:25-37",
  },
  {
    id: "nt-hard-52",
    book: "New Testament",
    chapter: "John",
    question: "What does Jesus say He is in John 8:12?",
    options: [
      [
        "The Light of the world",
        "The Bread of life",
        "The Good Shepherd",
        "The True Vine",
      ],
    ],
    answer: "The Light of the world",
    level: "hard",
    hint: "John 8:12",
  },
  {
    id: "nt-hard-53",
    book: "New Testament",
    chapter: "Acts",
    question:
      "In Acts 2, what miraculous event happens that enables the apostles to speak in different languages?",
    options: [
      [
        "The outpouring of the Holy Spirit",
        "A miraculous healing",
        "The raising of a dead man",
        "Walking on water",
      ],
    ],
    answer: "The outpouring of the Holy Spirit",
    level: "hard",
    hint: "Acts 2:1-4",
  },
  {
    id: "nt-hard-54",
    book: "New Testament",
    chapter: "Romans",
    question:
      'What does Paul describe as the "law of the Spirit of life" in Romans 8?',
    options: [
      [
        "The guiding force that frees believers from the law of sin and death",
        "The Mosaic Law",
        "The Ten Commandments",
        "Natural law",
      ],
    ],
    answer:
      "The guiding force that frees believers from the law of sin and death",
    level: "hard",
    hint: "Romans 8:2-4",
  },
  {
    id: "nt-hard-55",
    book: "New Testament",
    chapter: "1 Corinthians",
    question:
      "In 1 Corinthians 15, what analogy does Paul use to explain the resurrection body?",
    options: [
      [
        "A seed must die to produce a new plant",
        "A garment must be discarded to wear a new one",
        "A building must be torn down to build a new one",
        "A book must be closed to write a new chapter",
      ],
    ],
    answer: "A seed must die to produce a new plant",
    level: "hard",
    hint: "1 Corinthians 15:35-44",
  },
  {
    id: "nt-hard-56",
    book: "New Testament",
    chapter: "Galatians",
    question:
      "In Galatians 5:4, what does Paul say about those who seek to be justified by the law?",
    options: [
      [
        "They have fallen away from grace",
        "They will be blessed",
        "They will attain perfection",
        "They will lead the church",
      ],
    ],
    answer: "They have fallen away from grace",
    level: "hard",
    hint: "Galatians 5:4",
  },
  {
    id: "nt-hard-57",
    book: "New Testament",
    chapter: "Ephesians",
    question: 'What does Paul describe as the "mystery" in Ephesians 3:6?',
    options: [
      [
        "The inclusion of Gentiles in the church",
        "The resurrection of the dead",
        "The second coming of Christ",
        "The nature of the Trinity",
      ],
    ],
    answer: "The inclusion of Gentiles in the church",
    level: "hard",
    hint: "Ephesians 3:6",
  },
  {
    id: "nt-hard-58",
    book: "New Testament",
    chapter: "Philippians",
    question: "In Philippians 2:6-8, how does Paul describe Jesus’ attitude?",
    options: [
      [
        "He humbled Himself by becoming obedient to death on a cross",
        "He sought glory and honor",
        "He ignored human suffering",
        "He accumulated wealth",
      ],
    ],
    answer: "He humbled Himself by becoming obedient to death on a cross",
    level: "hard",
    hint: "Philippians 2:6-8",
  },
  {
    id: "nt-hard-59",
    book: "New Testament",
    chapter: "James",
    question:
      "What does James argue is the relationship between faith and deeds in James 2?",
    options: [
      [
        "Faith without deeds is dead",
        "Deeds are more important than faith",
        "Faith and deeds are unrelated",
        "Deeds negate the need for faith",
      ],
    ],
    answer: "Faith without deeds is dead",
    level: "hard",
    hint: "James 2:17",
  },
  {
    id: "nt-hard-60",
    book: "New Testament",
    chapter: "1 Peter",
    question:
      'In 1 Peter 2:9, believers are described as a "chosen people." What are they called?',
    options: [
      [
        "A royal priesthood",
        "A sacred congregation",
        "An elect nation",
        "A holy tribe",
      ],
    ],
    answer: "A royal priesthood",
    level: "hard",
    hint: "1 Peter 2:9",
  },
  {
    id: "nt-hard-61",
    book: "New Testament",
    chapter: "Hebrews",
    question:
      "According to Hebrews 4:12, what is sharper than any double-edged sword?",
    options: [["The word of God", "Faith", "Prayer", "Hope"]],
    answer: "The word of God",
    level: "hard",
    hint: "Hebrews 4:12",
  },
  {
    id: "nt-hard-62",
    book: "New Testament",
    chapter: "Revelation",
    question:
      "In Revelation 13, what power does the beast have over all tribes, peoples, languages, and nations?",
    options: [
      [
        "Authority to wage war against the saints",
        "Authority to build temples",
        "Authority to grant eternal life",
        "Authority to bestow riches",
      ],
    ],
    answer: "Authority to wage war against the saints",
    level: "hard",
    hint: "Revelation 13:7",
  },
  {
    id: "nt-hard-63",
    book: "New Testament",
    chapter: "Matthew",
    question:
      "In Matthew 28:19-20, what command does Jesus give to His disciples?",
    options: [
      [
        "Go and make disciples of all nations",
        "Build churches in every city",
        "Accumulate wealth and power",
        "Perform miracles to prove faith",
      ],
    ],
    answer: "Go and make disciples of all nations",
    level: "hard",
    hint: "Matthew 28:19-20",
  },
  {
    id: "nt-hard-64",
    book: "New Testament",
    chapter: "Mark",
    question:
      "In Mark 16, what specific instruction does Jesus give to the women at the tomb?",
    options: [
      [
        "Go tell His disciples and Peter",
        "Remain silent",
        "Build a monument",
        "Anoint His body with spices",
      ],
    ],
    answer: "Go tell His disciples and Peter",
    level: "hard",
    hint: "Mark 16:7",
  },
  {
    id: "nt-hard-65",
    book: "New Testament",
    chapter: "Luke",
    question:
      "In Luke 24:36-43, how does Jesus prove to His disciples that He is not a ghost?",
    options: [
      [
        "He eats broiled fish in their presence",
        "He speaks in riddles",
        "He disappears and reappears",
        "He performs a miracle",
      ],
    ],
    answer: "He eats broiled fish in their presence",
    level: "hard",
    hint: "Luke 24:36-43",
  },
  {
    id: "nt-hard-66",
    book: "New Testament",
    chapter: "John",
    question: "In John 14:6, what does Jesus declare Himself to be?",
    options: [
      [
        "The way, the truth, and the life",
        "The bread of life",
        "The good shepherd",
        "The light of the world",
      ],
    ],
    answer: "The way, the truth, and the life",
    level: "hard",
    hint: "John 14:6",
  },
  {
    id: "nt-hard-67",
    book: "New Testament",
    chapter: "Acts",
    question: "In Acts 9, on the road to Damascus, who speaks to Saul (Paul)?",
    options: [
      ["Jesus", "An angel", "Peter", "John"],
      ["Jesus", "An angel", "Peter", "John"],
    ],
    answer: "Jesus",
    level: "hard",
    hint: "Acts 9:3-6",
  },
  {
    id: "nt-hard-68",
    book: "New Testament",
    chapter: "Romans",
    question:
      "What does Paul explain about Israel’s partial hardening in Romans 11?",
    options: [
      [
        "It is only temporary and for the sake of the gospel",
        "It is permanent and absolute",
        "It signifies God’s rejection of Israel",
        "It is due to their moral failures",
      ],
    ],
    answer: "It is only temporary and for the sake of the gospel",
    level: "hard",
    hint: "Romans 11:25-26",
  },
  {
    id: "nt-hard-69",
    book: "New Testament",
    chapter: "1 Corinthians",
    question:
      "In 1 Corinthians 12, what does Paul describe as the body of Christ?",
    options: [
      [
        "The church with many members",
        "Only the apostles",
        "A physical body",
        "The Holy Spirit alone",
      ],
    ],
    answer: "The church with many members",
    level: "hard",
    hint: "1 Corinthians 12:12-27",
  },
  {
    id: "nt-hard-70",
    book: "New Testament",
    chapter: "Galatians",
    question: "In Galatians 6:14, what does Paul say about boasting?",
    options: [
      [
        "He will not boast except in the cross of our Lord Jesus Christ",
        "He will boast in his own achievements",
        "He will boast in wealth",
        "He will not boast at all",
      ],
    ],
    answer: "He will not boast except in the cross of our Lord Jesus Christ",
    level: "hard",
    hint: "Galatians 6:14",
  },
  {
    id: "nt-hard-71",
    book: "New Testament",
    chapter: "Ephesians",
    question:
      "In Ephesians 3:20, what does Paul say God can do beyond what we can ask or imagine?",
    options: [
      [
        "Exceedingly above all that we ask or think",
        "Provide physical wealth",
        "Control natural events",
        "Give us authority over others",
      ],
    ],
    answer: "Exceedingly above all that we ask or think",
    level: "hard",
    hint: "Ephesians 3:20",
  },
  {
    id: "nt-hard-72",
    book: "New Testament",
    chapter: "Philippians",
    question:
      "In Philippians 1:19, what does Paul say will happen through your prayers and the help of the Spirit of Jesus Christ?",
    options: [
      [
        "I will be delivered from bondage and will serve alongside you with joy",
        "I will receive wealth",
        "I will achieve personal success",
        "I will be exempt from suffering",
      ],
    ],
    answer:
      "I will be delivered from bondage and will serve alongside you with joy",
    level: "hard",
    hint: "Philippians 1:19",
  },
  {
    id: "nt-hard-73",
    book: "New Testament",
    chapter: "James",
    question: "In James 4:6, what does God give to the humble?",
    options: [["Grace", "Wealth", "Power", "Wisdom"]],
    answer: "Grace",
    level: "hard",
    hint: "James 4:6",
  },
  {
    id: "nt-hard-74",
    book: "New Testament",
    chapter: "1 Peter",
    question:
      "In 1 Peter 3:15, what are believers instructed to always be ready to give?",
    options: [
      [
        "A defense of the hope that is in them",
        "Material offerings",
        "Excuses for their actions",
        "Tales of miracles",
      ],
    ],
    answer: "A defense of the hope that is in them",
    level: "hard",
    hint: "1 Peter 3:15",
  },
  {
    id: "nt-hard-75",
    book: "New Testament",
    chapter: "Hebrews",
    question:
      "According to Hebrews 6:19, what is the hope that we have as an anchor of the soul?",
    options: [
      [
        "The hope set before us",
        "The hope of wealth",
        "The hope of earthly glory",
        "The hope of avoiding suffering",
      ],
    ],
    answer: "The hope set before us",
    level: "hard",
    hint: "Hebrews 6:19",
  },
];


const newTestament = [...newTestamentEasy, ...newTestamentMedium, ...newTestamentHard]

export default newTestament