const oldTestamentEasy = [
    {
      id: 'ot-easy-1',
      book: 'Old Testament',
      chapter: 'Genesis',
      question: 'Who was the first man created by God?',
      options: ['Adam', 'Noah', 'Abraham', 'Moses'],
      answer: 'Adam',
      level: 'easy',
      hint: 'Genesis 2:7',
    },
    {
      id: 'ot-easy-2',
      book: 'Old Testament',
      chapter: 'Exodus',
      question: 'What was the name of the sea that Moses parted?',
      options: ['Red Sea', 'Dead Sea', 'Mediterranean Sea', 'Sea of Galilee'],
      answer: 'Red Sea',
      level: 'easy',
      hint: 'Exodus 14:21-22',
    },
    {
      id: 'ot-easy-3',
      book: 'Old Testament',
      chapter: 'Leviticus',
      question: 'Which tribe did the Levites belong to?',
      options: ['Levi', 'Judah', 'Benjamin', 'Dan'],
      answer: 'Levi',
      level: 'easy',
      hint: 'Leviticus 1:1',
    },
    {
      id: 'ot-easy-4',
      book: 'Old Testament',
      chapter: 'Numbers',
      question: 'How many spies did Moses send to Canaan?',
      options: ['12', '10', '7', '24'],
      answer: '12',
      level: 'easy',
      hint: 'Numbers 13:1-2',
    },
    {
      id: 'ot-easy-5',
      book: 'Old Testament',
      chapter: 'Deuteronomy',
      question: 'Who led the Israelites into the Promised Land?',
      options: ['Joshua', 'Moses', 'Caleb', 'Aaron'],
      answer: 'Joshua',
      level: 'easy',
      hint: 'Deuteronomy 34:9',
    },
    {
      id: 'ot-easy-6',
      book: 'Old Testament',
      chapter: 'Joshua',
      question: 'What was the name of the city that the Israelites famously conquered by marching around its walls?',
      options: ['Jericho', 'Ai', 'Hebron', 'Gibeon'],
      answer: 'Jericho',
      level: 'easy',
      hint: 'Joshua 6:1-20',
    },
    {
      id: 'ot-easy-7',
      book: 'Old Testament',
      chapter: 'Judges',
      question: 'Who was the judge known for his superhuman strength?',
      options: ['Samson', 'Gideon', 'Deborah', 'Jephthah'],
      answer: 'Samson',
      level: 'easy',
      hint: 'Judges 13-16',
    },
    {
      id: 'ot-easy-8',
      book: 'Old Testament',
      chapter: 'Ruth',
      question: 'Ruth is a Moabite woman who became the great-grandmother of which king?',
      options: ['David', 'Solomon', 'Saul', 'Hezekiah'],
      answer: 'David',
      level: 'easy',
      hint: 'Ruth 4:18-22',
    },
    {
      id: 'ot-easy-9',
      book: 'Old Testament',
      chapter: '1 Samuel',
      question: 'Who was the first king of Israel?',
      options: ['Saul', 'David', 'Solomon', 'Samuel'],
      answer: 'Saul',
      level: 'easy',
      hint: '1 Samuel 9:17-27',
    },
    {
      id: 'ot-easy-10',
      book: 'Old Testament',
      chapter: '2 Samuel',
      question: 'Who was David’s loyal friend who died while protecting him?',
      options: ['Jonathan', 'Abner', 'Joab', 'Ish-bosheth'],
      answer: 'Jonathan',
      level: 'easy',
      hint: '2 Samuel 1:17-27',
    },
    {
      id: 'ot-easy-11',
      book: 'Old Testament',
      chapter: '1 Kings',
      question: 'Who built the first Temple in Jerusalem?',
      options: ['Solomon', 'David', 'Hezekiah', 'Josiah'],
      answer: 'Solomon',
      level: 'easy',
      hint: '1 Kings 6',
    },
    {
      id: 'ot-easy-12',
      book: 'Old Testament',
      chapter: '2 Kings',
      question: 'Which prophet confronted King Ahab and predicted the downfall of his house?',
      options: ['Elijah', 'Elisha', 'Isaiah', 'Jeremiah'],
      answer: 'Elijah',
      level: 'easy',
      hint: '1 Kings 21',
    },
    {
      id: 'ot-easy-13',
      book: 'Old Testament',
      chapter: '1 Chronicles',
      question: 'Which king is prominently featured in 1 Chronicles?',
      options: ['David', 'Solomon', 'Saul', 'Hezekiah'],
      answer: 'David',
      level: 'easy',
      hint: '1 Chronicles 10-29',
    },
    {
      id: 'ot-easy-14',
      book: 'Old Testament',
      chapter: '2 Chronicles',
      question: 'Which king of Judah was known for his religious reforms?',
      options: ['Hezekiah', 'Manasseh', 'Jehoiakim', 'Jehoshaphat'],
      answer: 'Hezekiah',
      level: 'easy',
      hint: '2 Chronicles 29-32',
    },
    {
      id: 'ot-easy-15',
      book: 'Old Testament',
      chapter: 'Ezra',
      question: 'What was Ezra’s role in the return from exile?',
      options: ['Priest and scribe', 'King', 'Prophet', 'Judge'],
      answer: 'Priest and scribe',
      level: 'easy',
      hint: 'Ezra 7:6',
    },
    {
      id: 'ot-easy-16',
      book: 'Old Testament',
      chapter: 'Nehemiah',
      question: 'What did Nehemiah rebuild in Jerusalem?',
      options: ['The walls', 'The temple', 'The marketplace', 'The palaces'],
      answer: 'The walls',
      level: 'easy',
      hint: 'Nehemiah 2:17-18',
    },
    {
      id: 'ot-easy-17',
      book: 'Old Testament',
      chapter: 'Esther',
      question: 'Who became queen of Persia and saved her people?',
      options: ['Esther', 'Vashti', 'Athaliah', 'Jezebel'],
      answer: 'Esther',
      level: 'easy',
      hint: 'Esther 4:14',
    },
    {
      id: 'ot-easy-18',
      book: 'Old Testament',
      chapter: 'Job',
      question: 'What was Job’s occupation before his trials?',
      options: ['Shepherd', 'Farmer', 'Merchant', 'Blacksmith'],
      answer: 'Shepherd',
      level: 'easy',
      hint: 'Job 1:1',
    },
    {
      id: 'ot-easy-19',
      book: 'Old Testament',
      chapter: 'Psalms',
      question: 'Who is traditionally credited with writing many of the Psalms?',
      options: ['David', 'Solomon', 'Moses', 'Isaiah'],
      answer: 'David',
      level: 'easy',
      hint: 'Psalms 23',
    },
    {
      id: 'ot-easy-20',
      book: 'Old Testament',
      chapter: 'Proverbs',
      question: 'Which king is attributed with writing the Book of Proverbs?',
      options: ['Solomon', 'David', 'Saul', 'Hezekiah'],
      answer: 'Solomon',
      level: 'easy',
      hint: 'Proverbs 1:1',
    },
    {
      id: 'ot-easy-21',
      book: 'Old Testament',
      chapter: 'Ecclesiastes',
      question: 'Who is the author of Ecclesiastes?',
      options: ['Qoheleth', 'Solomon', 'David', 'Isaiah'],
      answer: 'Qoheleth',
      level: 'easy',
      hint: 'Ecclesiastes 1:1',
    },
    {
      id: 'ot-easy-22',
      book: 'Old Testament',
      chapter: 'Song of Solomon',
      question: 'What is the primary theme of the Song of Solomon?',
      options: ['Love', 'War', 'Wisdom', 'Justice'],
      answer: 'Love',
      level: 'easy',
      hint: 'Song of Solomon 1:2',
    },
    {
      id: 'ot-easy-23',
      book: 'Old Testament',
      chapter: 'Isaiah',
      question: 'Which prophet saw the vision of God seated on a throne in Isaiah 6?',
      options: ['Isaiah', 'Jeremiah', 'Ezekiel', 'Daniel'],
      answer: 'Isaiah',
      level: 'easy',
      hint: 'Isaiah 6:1-8',
    },
    {
      id: 'ot-easy-24',
      book: 'Old Testament',
      chapter: 'Jeremiah',
      question: 'What city did Jeremiah prophesy would be destroyed?',
      options: ['Jerusalem', 'Babylon', 'Nineveh', 'Tyre'],
      answer: 'Jerusalem',
      level: 'easy',
      hint: 'Jeremiah 25:8',
    },
    {
      id: 'ot-easy-25',
      book: 'Old Testament',
      chapter: 'Lamentations',
      question: 'What event is primarily described in the Book of Lamentations?',
      options: ['Destruction of Jerusalem', 'Exodus from Egypt', 'Rebuilding the Temple', 'Moses receiving the Ten Commandments'],
      answer: 'Destruction of Jerusalem',
      level: 'easy',
      hint: 'Lamentations 1:1',
    },
    {
      id: 'ot-easy-26',
      book: 'Old Testament',
      chapter: 'Ezekiel',
      question: 'What unique feature did Ezekiel’s vision of the valley of dry bones have?',
      options: ['Bones coming together and being covered with flesh', 'A burning bush', 'A great flood', 'A rainbow'],
      answer: 'Bones coming together and being covered with flesh',
      level: 'easy',
      hint: 'Ezekiel 37:1-14',
    },
    {
      id: 'ot-easy-27',
      book: 'Old Testament',
      chapter: 'Daniel',
      question: 'What animal did Daniel survive being thrown into?',
      options: ['Lion\'s den', 'Grizzly bear enclosure', 'Snake pit', 'Bear cage'],
      answer: 'Lion\'s den',
      level: 'easy',
      hint: 'Daniel 6:16-23',
    },
    {
      id: 'ot-easy-28',
      book: 'Old Testament',
      chapter: 'Hosea',
      question: 'Hosea’s marriage to Gomer symbolizes what relationship?',
      options: ['God’s relationship with Israel', 'Marriage in ancient Israel', 'Political alliances', 'Sibling relationships'],
      answer: 'God’s relationship with Israel',
      level: 'easy',
      hint: 'Hosea 1:2-9',
    },
    {
      id: 'ot-easy-29',
      book: 'Old Testament',
      chapter: 'Joel',
      question: 'What natural disaster is used as a metaphor in Joel to describe the coming judgment?',
      options: ['Locust plague', 'Earthquake', 'Flood', 'Drought'],
      answer: 'Locust plague',
      level: 'easy',
      hint: 'Joel 1:4',
    },
    {
      id: 'ot-easy-30',
      book: 'Old Testament',
      chapter: 'Amos',
      question: 'Amos was a prophet to which kingdom?',
      options: ['Israel', 'Judah', 'Babylon', 'Assyria'],
      answer: 'Israel',
      level: 'easy',
      hint: 'Amos 1:1',
    },
    {
      id: 'ot-easy-31',
      book: 'Old Testament',
      chapter: 'Obadiah',
      question: 'The Book of Obadiah prophesies against which nation?',
      options: ['Edom', 'Egypt', 'Moab', 'Assyria'],
      answer: 'Edom',
      level: 'easy',
      hint: 'Obadiah 1:1',
    },
    {
      id: 'ot-easy-32',
      book: 'Old Testament',
      chapter: 'Jonah',
      question: 'What large fish swallowed Jonah?',
      options: ['Great fish (whale)', 'Shark', 'Sea monster', 'Dolphin'],
      answer: 'Great fish (whale)',
      level: 'easy',
      hint: 'Jonah 1:17',
    },
    {
      id: 'ot-easy-33',
      book: 'Old Testament',
      chapter: 'Micah',
      question: 'According to Micah 6:8, what does the Lord require of you?',
      options: ['To act justly, love mercy, and walk humbly with God', 'To build temples', 'To offer sacrifices', 'To observe strict laws'],
      answer: 'To act justly, love mercy, and walk humbly with God',
      level: 'easy',
      hint: 'Micah 6:8',
    },
    {
      id: 'ot-easy-34',
      book: 'Old Testament',
      chapter: 'Nahum',
      question: 'Nahum prophesies the downfall of which major city?',
      options: ['Nineveh', 'Jerusalem', 'Tyre', 'Sidon'],
      answer: 'Nineveh',
      level: 'easy',
      hint: 'Nahum 1:1-3',
    },
  ];

  const oldTestamentMedium = [
    // 1-35: Medium Questions
    {
      id: 'ot-medium-1',
      book: 'Old Testament',
      chapter: 'Genesis',
      question: 'What was the name of Abraham’s wife?',
      options: ['Sarah', 'Hagar', 'Rebekah', 'Leah'],
      answer: 'Sarah',
      level: 'medium',
      hint: 'Genesis 17:15-16',
    },
    {
      id: 'ot-medium-2',
      book: 'Old Testament',
      chapter: 'Exodus',
      question: 'What were the ten plagues that God sent upon Egypt intended to demonstrate?',
      options: ['God’s power over Pharaoh and Egypt', 'Punishment for the Israelites', 'A test for Moses', 'Divine approval of Pharaoh’s actions'],
      answer: 'God’s power over Pharaoh and Egypt',
      level: 'medium',
      hint: 'Exodus 7-12',
    },
    {
      id: 'ot-medium-3',
      book: 'Old Testament',
      chapter: 'Leviticus',
      question: 'What is the primary focus of the Book of Leviticus?',
      options: ['Laws and rituals for worship', 'Historical accounts of Israel', 'Prophecies about the Messiah', 'Stories of the patriarchs'],
      answer: 'Laws and rituals for worship',
      level: 'medium',
      hint: 'Leviticus 1:1-2',
    },
    {
      id: 'ot-medium-4',
      book: 'Old Testament',
      chapter: 'Numbers',
      question: 'Why were the Israelites wandering in the desert for 40 years?',
      options: ['Because of their lack of faith and disobedience', 'Due to enemy attacks', 'Because of a natural disaster', 'To explore the land'],
      answer: 'Because of their lack of faith and disobedience',
      level: 'medium',
      hint: 'Numbers 14:26-35',
    },
    {
      id: 'ot-medium-5',
      book: 'Old Testament',
      chapter: 'Deuteronomy',
      question: 'What is the Shema, found in Deuteronomy 6:4-5?',
      options: ['A central declaration of the Jewish faith', 'A prayer for peace', 'A commandment to build altars', 'A song of praise'],
      answer: 'A central declaration of the Jewish faith',
      level: 'medium',
      hint: 'Deuteronomy 6:4-5',
    },
    {
      id: 'ot-medium-6',
      book: 'Old Testament',
      chapter: 'Joshua',
      question: 'How did the Israelites cross the Jordan River?',
      options: ['By the waters stopping up', 'Using boats', 'By swimming', 'By building a bridge'],
      answer: 'By the waters stopping up',
      level: 'medium',
      hint: 'Joshua 3:14-17',
    },
    {
      id: 'ot-medium-7',
      book: 'Old Testament',
      chapter: 'Judges',
      question: 'Which judge delivered Israel from the Moabites and then ruled for 18 years?',
      options: ['Ehud', 'Othniel', 'Deborah', 'Gideon'],
      answer: 'Ehud',
      level: 'medium',
      hint: 'Judges 3:12-30',
    },
    {
      id: 'ot-medium-8',
      book: 'Old Testament',
      chapter: 'Ruth',
      question: 'How is Boaz related to Naomi in the Book of Ruth?',
      options: ['He is her kinsman-redeemer', 'He is her brother', 'He is her uncle', 'He is her cousin'],
      answer: 'He is her kinsman-redeemer',
      level: 'medium',
      hint: 'Ruth 4:1-10',
    },
    {
      id: 'ot-medium-9',
      book: 'Old Testament',
      chapter: '1 Samuel',
      question: 'Why did God reject Saul as king?',
      options: ['Because of his disobedience and incomplete obedience', 'Because he was too young', 'Because he wasn’t a Levite', 'Because he lacked wealth'],
      answer: 'Because of his disobedience and incomplete obedience',
      level: 'medium',
      hint: '1 Samuel 15:22-23',
    },
    {
      id: 'ot-medium-10',
      book: 'Old Testament',
      chapter: '2 Samuel',
      question: 'What significant event happened during David’s reign involving Bathsheba?',
      options: ['He committed adultery with her and arranged for her husband\'s death', 'He built a palace for her', 'He appointed her as queen', 'He married her immediately'],
      answer: 'He committed adultery with her and arranged for her husband\'s death',
      level: 'medium',
      hint: '2 Samuel 11:1-27',
    },
    {
      id: 'ot-medium-11',
      book: 'Old Testament',
      chapter: '1 Kings',
      question: 'What led to the division of the united kingdom of Israel into Israel and Judah?',
      options: ['Rehoboam\'s harsh policies and the ten tribes rejecting him', 'Solomon\'s wealth', 'A prophecy', 'Foreign invasion'],
      answer: 'Rehoboam\'s harsh policies and the ten tribes rejecting him',
      level: 'medium',
      hint: '1 Kings 12:16-20',
    },
    {
      id: 'ot-medium-12',
      book: 'Old Testament',
      chapter: '2 Kings',
      question: 'Which king of Israel was known for his extensive building projects and idol worship?',
      options: ['Manasseh', 'Ahab', 'Jehu', 'Jeroboam'],
      answer: 'Manasseh',
      level: 'medium',
      hint: '2 Kings 21:1-18',
    },
    {
      id: 'ot-medium-13',
      book: 'Old Testament',
      chapter: '1 Chronicles',
      question: 'What major event in David’s life is detailed in 1 Chronicles 11?',
      options: ['Gathering of the mighty men of valor', 'His battle with Goliath', 'His exile from Judah', 'His dream of the temple'],
      answer: 'Gathering of the mighty men of valor',
      level: 'medium',
      hint: '1 Chronicles 11',
    },
    {
      id: 'ot-medium-14',
      book: 'Old Testament',
      chapter: '2 Chronicles',
      question: 'Which king of Judah rebuilt the Temple after it was destroyed by the Babylonians?',
      options: ['Zedekiah', 'Jehoiakim', 'Jehoiachin', 'Jehoiakim'],
      answer: 'Jehoiakim',
      level: 'medium',
      hint: '2 Chronicles 36',
    },
    {
      id: 'ot-medium-15',
      book: 'Old Testament',
      chapter: 'Ezra',
      question: 'What significant religious reform did Ezra lead?',
      options: ['Re-establishing the Torah and observing the Law', 'Building new altars', 'Introducing new sacrifices', 'Establishing a new priesthood'],
      answer: 'Re-establishing the Torah and observing the Law',
      level: 'medium',
      hint: 'Ezra 7:10',
    },
    {
      id: 'ot-medium-16',
      book: 'Old Testament',
      chapter: 'Nehemiah',
      question: 'What opposition did Nehemiah face while rebuilding the walls of Jerusalem?',
      options: ['Mockery, threats, and attempts to stop the work', 'Natural disasters', 'Lack of resources', 'Internal conflicts'],
      answer: 'Mockery, threats, and attempts to stop the work',
      level: 'medium',
      hint: 'Nehemiah 4',
    },
    {
      id: 'ot-medium-17',
      book: 'Old Testament',
      chapter: 'Esther',
      question: 'What was Haman’s plan against the Jews in Persia?',
      options: ['To destroy all Jews in the empire', 'To exile them', 'To convert them', 'To enslave them'],
      answer: 'To destroy all Jews in the empire',
      level: 'medium',
      hint: 'Esther 3:6',
    },
    {
      id: 'ot-medium-18',
      book: 'Old Testament',
      chapter: 'Job',
      question: 'What is the central theme of the Book of Job?',
      options: ['The righteousness of God and the problem of suffering', 'The creation of the world', 'The exodus from Egypt', 'The building of the Temple'],
      answer: 'The righteousness of God and the problem of suffering',
      level: 'medium',
      hint: 'Job 1:1-12',
    },
    {
      id: 'ot-medium-19',
      book: 'Old Testament',
      chapter: 'Psalms',
      question: 'Which Psalm is known as the Shepherd Psalm?',
      options: ['Psalm 23', 'Psalm 1', 'Psalm 51', 'Psalm 150'],
      answer: 'Psalm 23',
      level: 'medium',
      hint: 'Psalm 23',
    },
    {
      id: 'ot-medium-20',
      book: 'Old Testament',
      chapter: 'Proverbs',
      question: 'What is the primary purpose of the Book of Proverbs?',
      options: ['To impart wisdom and discipline', 'To narrate historical events', 'To prophesy future events', 'To document laws'],
      answer: 'To impart wisdom and discipline',
      level: 'medium',
      hint: 'Proverbs 1:2',
    },
    {
      id: 'ot-medium-21',
      book: 'Old Testament',
      chapter: 'Ecclesiastes',
      question: 'What recurring theme is explored in the Book of Ecclesiastes?',
      options: ['The meaninglessness of worldly pursuits', 'The power of prayer', 'The importance of sacrifice', 'The laws of inheritance'],
      answer: 'The meaninglessness of worldly pursuits',
      level: 'medium',
      hint: 'Ecclesiastes 1:2',
    },
    {
      id: 'ot-medium-22',
      book: 'Old Testament',
      chapter: 'Song of Solomon',
      question: 'What is the main subject of the Song of Solomon?',
      options: ['Romantic love between a bride and groom', 'The struggles of the Israelites', 'The wisdom of Solomon', 'Prophecies of the Messiah'],
      answer: 'Romantic love between a bride and groom',
      level: 'medium',
      hint: 'Song of Solomon 1:2',
    },
    {
      id: 'ot-medium-23',
      book: 'Old Testament',
      chapter: 'Isaiah',
      question: 'What significant prophecy is found in Isaiah 53?',
      options: ['The suffering servant', 'The rebuilding of Jerusalem', 'The fall of Babylon', 'The rise of Cyrus'],
      answer: 'The suffering servant',
      level: 'medium',
      hint: 'Isaiah 53',
    },
    {
      id: 'ot-medium-24',
      book: 'Old Testament',
      chapter: 'Jeremiah',
      question: 'What covenant does Jeremiah emphasize in his prophecies?',
      options: ['A new covenant based on the law written on hearts', 'An old covenant based on the tablets', 'A covenant with the Philistines', 'A political alliance'],
      answer: 'A new covenant based on the law written on hearts',
      level: 'medium',
      hint: 'Jeremiah 31:31-34',
    },
    {
      id: 'ot-medium-25',
      book: 'Old Testament',
      chapter: 'Lamentations',
      question: 'Who is traditionally credited with writing the Book of Lamentations?',
      options: ['Jeremiah', 'Ezekiel', 'Isaiah', 'Daniel'],
      answer: 'Jeremiah',
      level: 'medium',
      hint: 'Lamentations 1:1',
    },
    {
      id: 'ot-medium-26',
      book: 'Old Testament',
      chapter: 'Ezekiel',
      question: 'What vision does Ezekiel receive in the first chapter of his book?',
      options: ['The glory of God and the cherubim', 'A burning bush', 'A valley of dry bones', 'A ladder reaching to heaven'],
      answer: 'The glory of God and the cherubim',
      level: 'medium',
      hint: 'Ezekiel 1:1-28',
    },
    {
      id: 'ot-medium-27',
      book: 'Old Testament',
      chapter: 'Daniel',
      question: 'What interpretation did Daniel provide for Nebuchadnezzar’s dream about a statue made of various metals?',
      options: [
        'It represented successive kingdoms, starting with Babylon', 
        'It was a literal depiction of the future', 
        'It symbolized the rise and fall of prophets', 
        'It foretold the coming of the Messiah'],
      answer: 'It represented successive kingdoms, starting with Babylon',
      level: 'medium',
      hint: 'Daniel 2:31-45',
    },
    {
      id: 'ot-medium-28',
      book: 'Old Testament',
      chapter: 'Hosea',
      question: 'What does Hosea’s marriage to Gomer symbolize?',
      options: ['God’s unfaithfulness to Israel', 'Israel’s unfaithfulness to God', 'A political alliance', 'A model for marriages'],
      answer: 'Israel’s unfaithfulness to God',
      level: 'medium',
      hint: 'Hosea 1:2-9',
    },
    {
      id: 'ot-medium-29',
      book: 'Old Testament',
      chapter: 'Joel',
      question: 'What is the "Day of the Lord" as described in Joel?',
      options: ['A time of judgment and restoration', 'A new festival', 'The day of creation', 'The day of harvest'],
      answer: 'A time of judgment and restoration',
      level: 'medium',
      hint: 'Joel 2:1-32',
    },
    {
      id: 'ot-medium-30',
      book: 'Old Testament',
      chapter: 'Amos',
      question: 'What is the main message of the Book of Amos?',
      options: ['Social justice and condemnation of Israel\'s corruption', 'Building the Temple', 'Prophecies about the Messiah', 'Instructions for priests'],
      answer: 'Social justice and condemnation of Israel\'s corruption',
      level: 'medium',
      hint: 'Amos 5:21-24',
    },
    {
      id: 'ot-medium-31',
      book: 'Old Testament',
      chapter: 'Obadiah',
      question: 'Why is Edom condemned in the Book of Obadiah?',
      options: ['For rejoicing over Judah’s destruction', 'For idolatry', 'For alliance with Egypt', 'For supporting Israel'],
      answer: 'For rejoicing over Judah’s destruction',
      level: 'medium',
      hint: 'Obadiah 1:10',
    },
    {
      id: 'ot-medium-32',
      book: 'Old Testament',
      chapter: 'Jonah',
      question: 'What city was Jonah sent to preach repentance to?',
      options: ['Nineveh', 'Jerusalem', 'Tyre', 'Sidon'],
      answer: 'Nineveh',
      level: 'medium',
      hint: 'Jonah 1:1-2',
    },
    {
      id: 'ot-medium-33',
      book: 'Old Testament',
      chapter: 'Micah',
      question: 'What future king does Micah prophesy will come from Bethlehem?',
      options: ['The Messiah (Jesus)', 'King Solomon', 'King David', 'King Hezekiah'],
      answer: 'The Messiah (Jesus)',
      level: 'medium',
      hint: 'Micah 5:2',
    },
    {
      id: 'ot-medium-34',
      book: 'Old Testament',
      chapter: 'Nahum',
      question: 'What is the primary focus of the Book of Nahum?',
      options: ['The downfall of Nineveh', 'The rebuilding of Jerusalem', 'The exodus from Egypt', 'The reign of Solomon'],
      answer: 'The downfall of Nineveh',
      level: 'medium',
      hint: 'Nahum 1:1-3',
    },
  ];

  const oldTestamentHard = [
    // 1-35: Hard Questions
    {
      id: 'ot-hard-1',
      book: 'Old Testament',
      chapter: 'Genesis',
      question: 'What was the original name of Abram before God changed it?',
      options: ['Abram', 'Abraham', 'Lot', 'Terah'],
      answer: 'Abram',
      level: 'hard',
      hint: 'Genesis 17:5',
    },
    {
      id: 'ot-hard-2',
      book: 'Old Testament',
      chapter: 'Exodus',
      question: 'What was the significance of the Passover lamb\'s blood on the doorposts?',
      options: [
        'It signified the Israelites were to be spared from the plague of the firstborn',
        'It was a sign of sacrifice to God',
        'It was meant to honor the Egyptian gods',
        'It indicated the end of slavery'],
      answer: 'It signified the Israelites were to be spared from the plague of the firstborn',
      level: 'hard',
      hint: 'Exodus 12:13',
    },
    {
      id: 'ot-hard-3',
      book: 'Old Testament',
      chapter: 'Leviticus',
      question: 'What is the purpose of the Day of Atonement (Yom Kippur) as described in Leviticus?',
      options: [
        'To make atonement for the sins of the people',
        'To celebrate the harvest',
        'To commemorate the exodus from Egypt',
        'To honor the Levitical priests'],
      answer: 'To make atonement for the sins of the people',
      level: 'hard',
      hint: 'Leviticus 16',
    },
    {
      id: 'ot-hard-4',
      book: 'Old Testament',
      chapter: 'Numbers',
      question: 'What was the significance of the silver trumpets in the Book of Numbers?',
      options: [
        'They were used to signal the Israelites during their journey and for worship',
        'They were a form of currency',
        'They were weapons in battle',
        'They were used exclusively by the priests'],
      answer: 'They were used to signal the Israelites during their journey and for worship',
      level: 'hard',
      hint: 'Numbers 10:1-10',
    },
    {
      id: 'ot-hard-5',
      book: 'Old Testament',
      chapter: 'Deuteronomy',
      question: 'What was the "Covenant Renewal" ceremony in Deuteronomy 29-30 about?',
      options: [
        'Reaffirming the covenant between God and Israel', 
        'Breaking the covenant with the surrounding nations',
        'Establishing a new covenant',
        'Ending the old covenant'],
      answer: 'Reaffirming the covenant between God and Israel',
      level: 'hard',
      hint: 'Deuteronomy 29-30',
    },
    {
      id: 'ot-hard-6',
      book: 'Old Testament',
      chapter: 'Joshua',
      question: 'How did the sun and moon behave during the battle of Gibeon?',
      options: [
        'The sun stood still and the moon stopped until victory was achieved', 
        'They appeared for the first time in the night', 
        'They were covered by clouds', 
        'They set earlier than usual'],
      answer: 'The sun stood still and the moon stopped until victory was achieved',
      level: 'hard',
      hint: 'Joshua 10:12-14',
    },
    {
      id: 'ot-hard-7',
      book: 'Old Testament',
      chapter: 'Judges',
      question: 'What unique weapon did Samson use to defeat the Philistines when his hair was cut?',
      options: [
        'A donkey\'s jawbone', 
        'A sword', 
        'A bow and arrow', 
        'A spear'],
      answer: 'A donkey\'s jawbone',
      level: 'hard',
      hint: 'Judges 15:15-17',
    },
    {
      id: 'ot-hard-8',
      book: 'Old Testament',
      chapter: 'Ruth',
      question: 'What is the significance of Ruth gleaning in Boaz\'s field?',
      options: [
        'It demonstrated her loyalty and provided for Naomi and herself', 
        'It was a punishment for her past', 
        'It was a form of worship', 
        'It was required by law'],
      answer: 'It demonstrated her loyalty and provided for Naomi and herself',
      level: 'hard',
      hint: 'Ruth 2',
    },
    {
      id: 'ot-hard-9',
      book: 'Old Testament',
      chapter: '1 Samuel',
      question: 'How did Samuel anoint David as king while Saul was still reigning?',
      options: [
        'In secret, while Saul was distracted', 
        'In a public ceremony', 
        'By force', 
        'With the knowledge of Saul'],
      answer: 'In secret, while Saul was distracted',
      level: 'hard',
      hint: '1 Samuel 16:1-13',
    },
    {
      id: 'ot-hard-10',
      book: 'Old Testament',
      chapter: '2 Samuel',
      question: 'What was the name of the palace that David built in Jerusalem?',
      options: ['Palace of David', 'Solomon\'s Temple', 'The Tent of Meeting', 'Zion Palace'],
      answer: 'Palace of David',
      level: 'hard',
      hint: '2 Samuel 5:9-10',
    },
    {
      id: 'ot-hard-11',
      book: 'Old Testament',
      chapter: '1 Kings',
      question: 'What led to Elijah fleeing from Jezebel?',
      options: [
        'Jezebel threatened his life after he defeated the prophets of Baal', 
        'He decided to retire', 
        'He wanted to travel', 
        'He was appointed to a new position'],
        answer: 'Jezebel threatened his life after he defeated the prophets of Baal',
        level: 'hard',
        hint: '1 Kings 19',
    },
    {
      id: 'ot-hard-12',
      book: 'Old Testament',
      chapter: '2 Kings',
      question: 'What miracle did Elisha perform to provide food for 100 men?',
      options: [
        'Multiplying a widow’s oil', 
        'Feeding them with loaves and fishes', 
        'Creating bread from stones', 
        'Summoning manna from heaven'],
        answer: 'Multiplying a widow’s oil',
        level: 'hard',
        hint: '2 Kings 4:1-7',
    },
    {
      id: 'ot-hard-13',
      book: 'Old Testament',
      chapter: '1 Chronicles',
      question: 'What significant census is recorded in 1 Chronicles?',
      options: [
        'The census of David’s mighty warriors', 
        'The census of the tribes of Israel', 
        'The census during the reign of Solomon', 
        'The census during the exile'],
        answer: 'The census of David’s mighty warriors',
        level: 'hard',
        hint: '1 Chronicles 11:10-47',
    },
    {
      id: 'ot-hard-14',
      book: 'Old Testament',
      chapter: '2 Chronicles',
      question: 'Which king is credited with the initial restoration of the Temple after the exile?',
      options: ['Hezekiah', 'Josiah', 'Zedekiah', 'Manasseh'],
      answer: 'Hezekiah',
      level: 'hard',
      hint: '2 Chronicles 29',
    },
    {
      id: 'ot-hard-15',
      book: 'Old Testament',
      chapter: 'Ezra',
      question: 'What issue did Ezra confront among the returning exiles?',
      options: [
        'Intermarriage with foreign women', 
        'Idolatry', 
        'Disobedience to the Law', 
        'Neglecting the temple'],
        answer: 'Intermarriage with foreign women',
        level: 'hard',
        hint: 'Ezra 9-10',
    },
    {
      id: 'ot-hard-16',
      book: 'Old Testament',
      chapter: 'Nehemiah',
      question: 'What leadership qualities did Nehemiah exhibit while rebuilding Jerusalem\'s walls?',
      options: [
        'Determination, prayerfulness, and strategic planning', 
        'Aggression and force', 
        'Isolation and secrecy', 
        'Delegation without involvement'],
        answer: 'Determination, prayerfulness, and strategic planning',
        level: 'hard',
        hint: 'Nehemiah 4:6; 1:4-11',
    },
    {
      id: 'ot-hard-17',
      book: 'Old Testament',
      chapter: 'Esther',
      question: 'How did Esther reveal her Jewish identity to King Xerxes?',
      options: [
        'She revealed it while pleading for her people', 
        'She never revealed it', 
        'She wrote a letter', 
        'She was forced to reveal it by Haman'],
        answer: 'She revealed it while pleading for her people',
        level: 'hard',
        hint: 'Esther 7:3-6',
    },
    {
      id: 'ot-hard-18',
      book: 'Old Testament',
      chapter: 'Job',
      question: 'What role does Elihu play in the Book of Job?',
      options: [
        'He offers a different perspective on Job’s suffering', 
        'He curses Job', 
        'He comforts Job', 
        'He is a friend of Job'],
        answer: 'He offers a different perspective on Job’s suffering',
        level: 'hard',
        hint: 'Job 32-37',
    },
    {
      id: 'ot-hard-19',
      book: 'Old Testament',
      chapter: 'Psalms',
      question: 'Which Psalm is a prophetic hymn about the Messiah’s suffering and death?',
      options: [
        'Psalm 22', 
        'Psalm 23', 
        'Psalm 100', 
        'Psalm 150'],
        answer: 'Psalm 22',
        level: 'hard',
        hint: 'Psalm 22:16-18',
    },
    {
      id: 'ot-hard-20',
      book: 'Old Testament',
      chapter: 'Proverbs',
      question: 'What is the “fear of the Lord” according to Proverbs 1:7?',
      options: [
        'The beginning of knowledge and wisdom', 
        'A reason to obey the law', 
        'A form of worship', 
        'A fear of punishment'],
        answer: 'The beginning of knowledge and wisdom',
        level: 'hard',
        hint: 'Proverbs 1:7',
    },
    {
      id: 'ot-hard-21',
      book: 'Old Testament',
      chapter: 'Ecclesiastes',
      question: 'What does Ecclesiastes 3:1-8 famously declare about time?',
      options: [
        'There is a time for everything', 
        'Time is an illusion', 
        'Time heals all wounds', 
        'Time is fleeting'],
        answer: 'There is a time for everything',
        level: 'hard',
        hint: 'Ecclesiastes 3:1-8',
    },
    {
      id: 'ot-hard-22',
      book: 'Old Testament',
      chapter: 'Song of Solomon',
      question: 'What literary genre best describes the Song of Solomon?',
      options: [
        'A poetic dialogue of love', 
        'A historical narrative', 
        'A prophetic vision', 
        'A wisdom proverb'],
        answer: 'A poetic dialogue of love',
        level: 'hard',
        hint: 'Song of Solomon 1:1',
    },
    {
      id: 'ot-hard-23',
      book: 'Old Testament',
      chapter: 'Isaiah',
      question: 'What is the “Immanuel” prophecy in Isaiah 7:14?',
      options: [
        'A virgin will conceive and bear a son, and his name will be Immanuel', 
        'A new king will be born', 
        'A great battle will ensue', 
        'A new covenant will be established'],
        answer: 'A virgin will conceive and bear a son, and his name will be Immanuel',
        level: 'hard',
        hint: 'Isaiah 7:14',
    },
    {
      id: 'ot-hard-24',
      book: 'Old Testament',
      chapter: 'Jeremiah',
      question: 'What does Jeremiah 29:11 say about God’s plans for His people?',
      options: [
        'Plans to prosper them and not to harm them', 
        'Plans to punish them', 
        'Plans to exile them', 
        'Plans to change their religion'],
        answer: 'Plans to prosper them and not to harm them',
        level: 'hard',
        hint: 'Jeremiah 29:11',
    },
    {
      id: 'ot-hard-25',
      book: 'Old Testament',
      chapter: 'Lamentations',
      question: 'What literary device is predominantly used in the Book of Lamentations?',
      options: [
        'Acrostic poetry', 
        'Narrative storytelling', 
        'Parables', 
        'Prophetic visions'],
        answer: 'Acrostic poetry',
        level: 'hard',
        hint: 'Lamentations 1:1-22',
    },
    {
      id: 'ot-hard-26',
      book: 'Old Testament',
      chapter: 'Ezekiel',
      question: 'What vision does Ezekiel see involving dry bones in Ezekiel 37?',
      options: [
        'A valley of dry bones being brought to life', 
        'A temple being rebuilt', 
        'A new covenant', 
        'A city in ruins'],
        answer: 'A valley of dry bones being brought to life',
        level: 'hard',
        hint: 'Ezekiel 37:1-14',
    },
    {
      id: 'ot-hard-27',
      book: 'Old Testament',
      chapter: 'Daniel',
      question: 'What is the significance of the handwriting on the wall in Daniel 5?',
      options: [
        'It predicted the fall of Babylon', 
        'It was a message from an angel', 
        'It symbolized Daniel’s future', 
        'It was a new law'],
        answer: 'It predicted the fall of Babylon',
        level: 'hard',
        hint: 'Daniel 5:5-28',
    },
    {
      id: 'ot-hard-28',
      book: 'Old Testament',
      chapter: 'Hosea',
      question: 'What does Hosea 11:1 prophesy about Israel?',
      options: [
        'They will return from Egypt', 
        'They will conquer Canaan', 
        'They will receive the Law', 
        'They will worship idols'],
      answer: 'They will return from Egypt',
      level: 'hard',
      hint: 'Hosea 11:1',
    },
    {
      id: 'ot-hard-29',
      book: 'Old Testament',
      chapter: 'Joel',
      question: 'What does Joel describe as the "Day of the Lord"?',
      options: [
        'A time of judgment and restoration', 
        'A day of harvest', 
        'A time of peace', 
        'The creation day'],
      answer: 'A time of judgment and restoration',
      level: 'hard',
      hint: 'Joel 2:1-32',
    },
    {
      id: 'ot-hard-30',
      book: 'Old Testament',
      chapter: 'Amos',
      question: 'What is the central theme of Amos 5:24?',
      options: [
        'Justice and righteousness should flow like a river', 
        'Blessed are the meek', 
        'The fall of Babylon', 
        'The creation of the world'],
      answer: 'Justice and righteousness should flow like a river',
      level: 'hard',
      hint: 'Amos 5:24',
    },
    {
      id: 'ot-hard-31',
      book: 'Old Testament',
      chapter: 'Obadiah',
      question: 'What specific action of Edom is condemned in Obadiah?',
      options: [
        'Violating kinship ties by aiding Israel’s enemies', 
        'Idolatry', 
        'King oppression', 
        'Building altars to foreign gods'],
      answer: 'Violating kinship ties by aiding Israel’s enemies',
      level: 'hard',
      hint: 'Obadiah 1:10-14',
    },
    {
      id: 'ot-hard-32',
      book: 'Old Testament',
      chapter: 'Jonah',
      question: 'Why did Jonah initially flee from God’s command to go to Nineveh?',
      options: [
        'He feared the Ninevites would repent and be saved', 
        'He was afraid of the journey', 
        'He did not believe God', 
        'He preferred to stay in Israel'],
      answer: 'He feared the Ninevites would repent and be saved',
      level: 'hard',
      hint: 'Jonah 4:2',
    },
    {
      id: 'ot-hard-33',
      book: 'Old Testament',
      chapter: 'Micah',
      question: 'What does Micah 6:8 emphasize as what the Lord requires?',
      options: [
        'To act justly, love mercy, and walk humbly with God', 
        'To build great temples', 
        'To offer numerous sacrifices', 
        'To follow the law meticulously'],
      answer: 'To act justly, love mercy, and walk humbly with God',
      level: 'hard',
      hint: 'Micah 6:8',
    },
    {
      id: 'ot-hard-34',
      book: 'Old Testament',
      chapter: 'Nahum',
      question: 'What prophecy is central to the Book of Nahum?',
      options: [
        'The destruction of Nineveh', 
        'The rebuilding of Jerusalem', 
        'The rise of Cyrus', 
        'The exile of Israel'],
      answer: 'The destruction of Nineveh',
      level: 'hard',
      hint: 'Nahum 1-3',
    },
  ];


  const oldTestament = [
    ...oldTestamentEasy,
    ...oldTestamentMedium,
    ...oldTestamentHard,
  ];
  
export default oldTestament