const exodus = [
    // Easy Questions
    {
      id: 'exodus-easy-1',
      book: 'Exodus',
      chapter: 1,
      question: 'Who was the Hebrew midwife who feared God and saved many Hebrew babies?',
      options: ['Shiphrah and Puah', 'Miriam and Aaron', 'Zipporah and Jethro', 'Deborah and Hannah'],
      answer: 'Shiphrah and Puah',
      level: 'easy',
      hint: 'Exodus 1:15-21',
    },
    {
      id: 'exodus-easy-2',
      book: 'Exodus',
      chapter: 2,
      question: 'Who found and saved Moses when he was placed in a basket on the Nile?',
      options: ['Pharaoh’s daughter', 'An Israelite shepherd', 'A Hebrew midwife', 'Jethro'],
      answer: 'Pharaoh’s daughter',
      level: 'easy',
      hint: 'Exodus 2:5-10',
    },
    {
      id: 'exodus-easy-3',
      book: 'Exodus',
      chapter: 3,
      question: 'What was the name of the mountain where God appeared to Moses in the burning bush?',
      options: ['Mount Horeb', 'Mount Sinai', 'Mount Zion', 'Mount Nebo'],
      answer: 'Mount Horeb',
      level: 'easy',
      hint: 'Exodus 3:1-6',
    },
    {
      id: 'exodus-easy-4',
      book: 'Exodus',
      chapter: 4,
      question: 'What sign did God give Moses to prove that He sent him?',
      options: ['Turning his staff into a snake', 'Making his hand leprous', 'Both A and B', 'None of the above'],
      answer: 'Both A and B',
      level: 'easy',
      hint: 'Exodus 4:3-7',
    },
    {
      id: 'exodus-easy-5',
      book: 'Exodus',
      chapter: 5,
      question: 'Who were the two Hebrew foremen that Pharaoh appointed to oversee the work?',
      options: ['Shammah and Tekoa', 'Zeruiah and Eliab', 'Nadab and Abihu', 'Miriam and Aaron'],
      answer: 'Shammah and Tekoa',
      level: 'easy',
      hint: 'Exodus 5:6',
    },
    {
      id: 'exodus-easy-6',
      book: 'Exodus',
      chapter: 7,
      question: 'What was the first plague that God sent upon Egypt?',
      options: ['Water turned to blood', 'Frogs', 'Locusts', 'Darkness'],
      answer: 'Water turned to blood',
      level: 'easy',
      hint: 'Exodus 7:14-24',
    },
    {
      id: 'exodus-easy-7',
      book: 'Exodus',
      chapter: 12,
      question: 'What event does the Passover commemorate?',
      options: ['The Israelites’ liberation from Egypt', 'The creation of the world', 'The giving of the Ten Commandments', 'The construction of the Tabernacle'],
      answer: 'The Israelites’ liberation from Egypt',
      level: 'easy',
      hint: 'Exodus 12:14',
    },
    {
      id: 'exodus-easy-8',
      book: 'Exodus',
      chapter: 14,
      question: 'What miraculous event allowed the Israelites to escape from Pharaoh’s army?',
      options: ['The parting of the Red Sea', 'An earthquake', 'A whirlwind', 'A divine fire'],
      answer: 'The parting of the Red Sea',
      level: 'easy',
      hint: 'Exodus 14:21-22',
    },
    {
      id: 'exodus-easy-9',
      book: 'Exodus',
      chapter: 16,
      question: 'What did God provide the Israelites to eat in the wilderness?',
      options: ['Manna and quail', 'Bread and fish', 'Olives and figs', 'Milk and honey'],
      answer: 'Manna and quail',
      level: 'easy',
      hint: 'Exodus 16:4-15',
    },
    {
      id: 'exodus-easy-10',
      book: 'Exodus',
      chapter: 20,
      question: 'What significant event happened at Mount Sinai in Exodus 20?',
      options: ['God gave Moses the Ten Commandments', 'The parting of the Red Sea', 'The construction of the Tabernacle', 'The sending of the spies'],
      answer: 'God gave Moses the Ten Commandments',
      level: 'easy',
      hint: 'Exodus 20:1-17',
    },
    
    // Medium Questions
    {
      id: 'exodus-medium-1',
      book: 'Exodus',
      chapter: 3,
      question: 'What was Moses’ response when God called him from the burning bush?',
      options: [
        '"Here I am."', 
        '"Who are you?"', 
        '"What do you want from me?"', 
        '"I will go and tell the people."'
      ],
      answer: '"Here I am."',
      level: 'medium',
      hint: 'Exodus 3:4',
    },
    {
      id: 'exodus-medium-2',
      book: 'Exodus',
      chapter: 4,
      question: 'What did God give Moses to perform miracles before Pharaoh?',
      options: ['His staff', 'A magic wand', 'A golden crown', 'A silver trumpet'],
      answer: 'His staff',
      level: 'medium',
      hint: 'Exodus 4:2-5',
    },
    {
      id: 'exodus-medium-3',
      book: 'Exodus',
      chapter: 5,
      question: 'What was Pharaoh’s response when Moses and Aaron requested the Israelites to worship God?',
      options: [
        '"You must leave Israel at once."', 
        '"The Lord is dead."', 
        '"Let the Israelites go, but sacrifice to your God in their land."', 
        '"I will make you my servants."'
      ],
      answer: '"Let the Israelites go, but sacrifice to your God in their land."',
      level: 'medium',
      hint: 'Exodus 5:1-2',
    },
    {
      id: 'exodus-medium-4',
      book: 'Exodus',
      chapter: 7,
      question: 'How did Moses and Aaron demonstrate God’s power to Pharaoh in Exodus 7?',
      options: [
        ['By turning the Nile into blood', 
         'By bringing frogs upon Egypt', 
         'By causing hail to fall', 
         'All of the above'],
        ['Only by turning the Nile into blood', 
         'Only by bringing frogs upon Egypt', 
         'Only by causing hail to fall', 
         'All of the above'],
        ['Only by causing hail to fall', 
         'Only by bringing frogs upon Egypt', 
         'Only by turning the Nile into blood', 
         'All of the above'],
        ['None of the above', 
         'Only by bringing frogs upon Egypt', 
         'Only by turning the Nile into blood', 
         'Only by causing hail to fall']
      ],
      answer: 'By turning the Nile into blood',
      level: 'medium',
      hint: 'Exodus 7:14-24',
    },
    {
      id: 'exodus-medium-5',
      book: 'Exodus',
      chapter: 12,
      question: 'What specific instructions were given for the Passover lamb?',
      options: [
        ['It must be a male without blemish', 
         'It must be a female without blemish', 
         'It can be any animal', 
         'It must be a goat'],
        ['It can be any animal', 
         'It must be a goat', 
         'It must be a female without blemish', 
         'It must be a male without blemish'],
        ['It must be a male without blemish', 
         'It must be a female without blemish', 
         'It must be a goat', 
         'It can be any animal'],
        ['It must be a female without blemish', 
         'It must be a male without blemish', 
         'It must be a goat', 
         'It can be any animal']
      ],
      answer: 'It must be a male without blemish',
      level: 'medium',
      hint: 'Exodus 12:5',
    },
    {
      id: 'exodus-medium-6',
      book: 'Exodus',
      chapter: 14,
      question: 'What strategy did God use to defeat Pharaoh’s army at the Red Sea?',
      options: [
        ['Parting the sea and drowning the Egyptians', 
         'Sending a mighty wind to blow them away', 
         'Creating a storm that sank their ships', 
         'Using fire to burn the army'],
        ['Sending a mighty wind to blow them away', 
         'Creating a storm that sank their ships', 
         'Using fire to burn the army', 
         'Parting the sea and drowning the Egyptians'],
        ['Creating a storm that sank their ships', 
         'Using fire to burn the army', 
         'Parting the sea and drowning the Egyptians', 
         'Sending a mighty wind to blow them away'],
        ['Using fire to burn the army', 
         'Parting the sea and drowning the Egyptians', 
         'Sending a mighty wind to blow them away', 
         'Creating a storm that sank their ships']
      ],
      answer: 'Parting the sea and drowning the Egyptians',
      level: 'medium',
      hint: 'Exodus 14:21-22',
    },
    {
      id: 'exodus-medium-7',
      book: 'Exodus',
      chapter: 16,
      question: 'How did the Israelites collect manna each day?',
      options: [
        ['They gathered it each morning before the sun rose', 
         'They collected it at night', 
         'They found it scattered throughout the land', 
         'They had it provided by the priests'],
        ['They collected it at night', 
         'They had it provided by the priests', 
         'They found it scattered throughout the land', 
         'They gathered it each morning before the sun rose'],
        ['They found it scattered throughout the land', 
         'They collected it at night', 
         'They gathered it each morning before the sun rose', 
         'They had it provided by the priests'],
        ['They had it provided by the priests', 
         'They found it scattered throughout the land', 
         'They collected it at night', 
         'They gathered it each morning before the sun rose']
      ],
      answer: 'They gathered it each morning before the sun rose',
      level: 'medium',
      hint: 'Exodus 16:4-5',
    },
    {
      id: 'exodus-medium-8',
      book: 'Exodus',
      chapter: 20,
      question: 'Which commandment forbids making idols?',
      options: [
        ['Second Commandment', 
         'First Commandment', 
         'Third Commandment', 
         'Fourth Commandment'],
        ['First Commandment', 
         'Third Commandment', 
         'Fourth Commandment', 
         'Second Commandment'],
        ['Third Commandment', 
         'Fourth Commandment', 
         'Second Commandment', 
         'First Commandment'],
        ['Fourth Commandment', 
         'Second Commandment', 
         'First Commandment', 
         'Third Commandment']
      ],
      answer: 'Second Commandment',
      level: 'medium',
      hint: 'Exodus 20:4-5',
    },
    {
      id: 'exodus-medium-9',
      book: 'Exodus',
      chapter: 24,
      question: 'What covenant did Moses make with God on Mount Sinai?',
      options: [
        ['The Mosaic Covenant', 
         'The Abrahamic Covenant', 
         'The Davidic Covenant', 
         'The New Covenant'],
        ['The Abrahamic Covenant', 
         'The Mosaic Covenant', 
         'The Davidic Covenant', 
         'The New Covenant'],
        ['The Davidic Covenant', 
         'The New Covenant', 
         'The Abrahamic Covenant', 
         'The Mosaic Covenant'],
        ['The New Covenant', 
         'The Abrahamic Covenant', 
         'The Mosaic Covenant', 
         'The Davidic Covenant']
      ],
      answer: 'The Mosaic Covenant',
      level: 'medium',
      hint: 'Exodus 24:7-8',
    },
    {
      id: 'exodus-medium-10',
      book: 'Exodus',
      chapter: 32,
      question: 'What did Aaron do while Moses was receiving the Ten Commandments?',
      options: [
        ['Made a golden calf for the people to worship', 
         'Built the Tabernacle', 
         'Prepared the Passover meal', 
         'Prayed for the Israelites'],
        ['Made a golden calf for the people to worship', 
         'Prayed for the Israelites', 
         'Built the Tabernacle', 
         'Prepared the Passover meal'],
        ['Prayed for the Israelites', 
         'Made a golden calf for the people to worship', 
         'Built the Tabernacle', 
         'Prepared the Passover meal'],
        ['Built the Tabernacle', 
         'Made a golden calf for the people to worship', 
         'Prepared the Passover meal', 
         'Prayed for the Israelites']
      ],
      answer: 'Made a golden calf for the people to worship',
      level: 'medium',
      hint: 'Exodus 32:1-6',
    },
    
    // Hard Questions
    {
      id: 'exodus-hard-1',
      book: 'Exodus',
      chapter: 3,
      question: 'What was the name of Moses’ father-in-law?',
      options: [
        ['Jethro', 'Reuel', 'Eliezer', 'Heber'], 
        ['Reuel', 'Eliezer', 'Heber', 'Jethro'], 
        ['Eliezer', 'Heber', 'Jethro', 'Reuel'], 
        ['Heber', 'Jethro', 'Reuel', 'Eliezer']
      ],
      answer: 'Jethro',
      level: 'hard',
      hint: 'Exodus 3:1',
    },
    {
      id: 'exodus-hard-2',
      book: 'Exodus',
      chapter: 7,
      question: 'What specific plagues did God send as signs before the Israelites?',
      options: [
        ['Water to blood, frogs, lice, flies, livestock pestilence, boils, hail, locusts, darkness, and death of the firstborn', 
         'Only water to blood and frogs', 
         'Only locusts and darkness', 
         ['None of the above']],
        ['Water to blood, frogs, lice, flies, livestock pestilence, boils, hail, locusts, darkness, and death of the firstborn', 
         'Only water to blood and frogs', 
         'Only locusts and darkness', 
         ['None of the above']],
        ['Only locusts and darkness', 
         'Only water to blood and frogs', 
         'Water to blood, frogs, lice, flies, livestock pestilence, boils, hail, locusts, darkness, and death of the firstborn', 
         ['None of the above']],
        ['Only water to blood and frogs', 
         'Only locusts and darkness', 
         ['None of the above'], 
         'Water to blood, frogs, lice, flies, livestock pestilence, boils, hail, locusts, darkness, and death of the firstborn']
      ],
      answer: 'Water to blood, frogs, lice, flies, livestock pestilence, boils, hail, locusts, darkness, and death of the firstborn',
      level: 'hard',
      hint: 'Exodus 7-12',
    },
    {
      id: 'exodus-hard-3',
      book: 'Exodus',
      chapter: 12,
      question: 'What was the significance of the blood on the doorposts during the first Passover?',
      options: [
        ['It signified that the house belonged to the Israelites, and the Lord would pass over it during the plague of the firstborn', 
         'It was a decorative tradition', 
         'It symbolized wealth and prosperity', 
         'It was a mark of shame'],
        ['It signified that the house belonged to the Israelites, and the Lord would pass over it during the plague of the firstborn', 
         'It was a decorative tradition', 
         'It symbolized wealth and prosperity', 
         'It was a mark of shame'],
        ['It symbolized wealth and prosperity', 
         'It was a mark of shame', 
         'It was a decorative tradition', 
         'It signified that the house belonged to the Israelites, and the Lord would pass over it during the plague of the firstborn'],
        ['It was a mark of shame', 
         'It symbolized wealth and prosperity', 
         'It signified that the house belonged to the Israelites, and the Lord would pass over it during the plague of the firstborn', 
         'It was a decorative tradition']
      ],
      answer: 'It signified that the house belonged to the Israelites, and the Lord would pass over it during the plague of the firstborn',
      level: 'hard',
      hint: 'Exodus 12:7-13',
    },
    {
      id: 'exodus-hard-4',
      book: 'Exodus',
      chapter: 14,
      question: 'What caused the waters of the Red Sea to return after the Israelites crossed?',
      options: [
        ['The Israelites’ pursuers drowned when the waters returned', 
         'A natural tidal event', 
         'Pharaoh prayed for mercy', 
         'A strong wind blew the waters back'],
        ['Pharaoh prayed for mercy', 
         'A natural tidal event', 
         'A strong wind blew the waters back', 
         'The Israelites’ pursuers drowned when the waters returned'],
        ['A strong wind blew the waters back', 
         'Pharaoh prayed for mercy', 
         'A natural tidal event', 
         'The Israelites’ pursuers drowned when the waters returned'],
        ['The Israelites’ pursuers drowned when the waters returned', 
         'A strong wind blew the waters back', 
         'Pharaoh prayed for mercy', 
         'A natural tidal event']
      ],
      answer: 'The Israelites’ pursuers drowned when the waters returned',
      level: 'hard',
      hint: 'Exodus 14:26-28',
    },
    {
      id: 'exodus-hard-5',
      book: 'Exodus',
      chapter: 20,
      question: 'Which commandment forbids coveting your neighbor’s wife?',
      options: [
        ['Tenth Commandment', 
         'Ninth Commandment', 
         'Eighth Commandment', 
         'Seventh Commandment'],
        ['Ninth Commandment', 
         'Eighth Commandment', 
         'Seventh Commandment', 
         'Tenth Commandment'],
        ['Eighth Commandment', 
         'Seventh Commandment', 
         'Tenth Commandment', 
         'Ninth Commandment'],
        ['Seventh Commandment', 
         'Tenth Commandment', 
         'Ninth Commandment', 
         'Eighth Commandment']
      ],
      answer: 'Tenth Commandment',
      level: 'hard',
      hint: 'Exodus 20:17',
    },
    {
      id: 'exodus-hard-6',
      book: 'Exodus',
      chapter: 24,
      question: 'What did Moses do to seal the covenant between God and the Israelites?',
      options: [
        ['He sprinkled blood on the altar and the people', 
         'He built a new altar', 
         'He offered a burnt sacrifice', 
         'He wrote the commandments on stone tablets'],
        ['He built a new altar', 
         'He offered a burnt sacrifice', 
         'He wrote the commandments on stone tablets', 
         'He sprinkled blood on the altar and the people'],
        ['He offered a burnt sacrifice', 
         'He wrote the commandments on stone tablets', 
         'He sprinkled blood on the altar and the people', 
         'He built a new altar'],
        ['He wrote the commandments on stone tablets', 
         'He sprinkled blood on the altar and the people', 
         'He built a new altar', 
         'He offered a burnt sacrifice']
      ],
      answer: 'He sprinkled blood on the altar and the people',
      level: 'hard',
      hint: 'Exodus 24:8',
    },
    {
      id: 'exodus-hard-7',
      book: 'Exodus',
      chapter: 32,
      question: 'What was the consequence for the Israelites worshiping the golden calf?',
      options: [
        ['About three thousand men died', 
         'Pharaoh enslaved them again', 
         'They were exiled to Babylon', 
         'Moses destroyed the altar'],
        ['Pharaoh enslaved them again', 
         'They were exiled to Babylon', 
         'About three thousand men died', 
         'Moses destroyed the altar'],
        ['They were exiled to Babylon', 
         'About three thousand men died', 
         'Pharaoh enslaved them again', 
         'Moses destroyed the altar'],
        ['Moses destroyed the altar', 
         'Pharaoh enslaved them again', 
         'They were exiled to Babylon', 
         'About three thousand men died']
      ],
      answer: 'About three thousand men died',
      level: 'hard',
      hint: 'Exodus 32:28',
    },
    {
      id: 'exodus-hard-8',
      book: 'Exodus',
      chapter: 34,
      question: 'After the incident with the golden calf, what did God renew with Moses?',
      options: [
        ['The covenant', 
         'A new set of commandments', 
         'The construction of the Tabernacle', 
         'The Israelites’ promises'],
        ['The covenant', 
         'A new set of commandments', 
         'The construction of the Tabernacle', 
         'The Israelites’ promises'],
        ['A new set of commandments', 
         'The Israelites’ promises', 
         'The construction of the Tabernacle', 
         'The covenant'],
        ['The construction of the Tabernacle', 
         'The covenant', 
         'A new set of commandments', 
         'The Israelites’ promises']
      ],
      answer: 'The covenant',
      level: 'hard',
      hint: 'Exodus 34:1-28',
    },
    {
      id: 'exodus-hard-9',
      book: 'Exodus',
      chapter: 40,
      question: 'What was completed in Exodus 40?',
      options: [
        ['The setting up of the Tabernacle', 
         'The construction of the Golden Calf', 
         'The parting of the Red Sea', 
         'The giving of the Ten Commandments'],
        ['The construction of the Golden Calf', 
         'The setting up of the Tabernacle', 
         'The parting of the Red Sea', 
         'The giving of the Ten Commandments'],
        ['The parting of the Red Sea', 
         'The giving of the Ten Commandments', 
         'The setting up of the Tabernacle', 
         'The construction of the Golden Calf'],
        ['The giving of the Ten Commandments', 
         'The setting up of the Tabernacle', 
         'The parting of the Red Sea', 
         'The construction of the Golden Calf']
      ],
      answer: 'The setting up of the Tabernacle',
      level: 'hard',
      hint: 'Exodus 40:34-38',
    },
    {
      id: 'exodus-hard-10',
      book: 'Exodus',
      chapter: 15,
      question: 'What song did Moses and Miriam lead the Israelites in after crossing the Red Sea?',
      options: [
        ['The Song of Moses (Song of the Sea)', 
         'The Song of Deborah', 
         'The Song of Miriam', 
         'The Song of Solomon'],
        ['The Song of Deborah', 
         'The Song of Solomon', 
         'The Song of Miriam', 
         'The Song of Moses (Song of the Sea)'],
        ['The Song of Miriam', 
         'The Song of Solomon', 
         'The Song of Moses (Song of the Sea)', 
         'The Song of Deborah'],
        ['The Song of Solomon', 
         'The Song of Moses (Song of the Sea)', 
         'The Song of Deborah', 
         'The Song of Miriam']
      ],
      answer: 'The Song of Moses (Song of the Sea)',
      level: 'hard',
      hint: 'Exodus 15:1-18',
    },
    {
      id: 'exodus-hard-11',
      book: 'Exodus',
      chapter: 19,
      question: 'What was the condition God set for the Israelites to receive the Ten Commandments at Mount Sinai?',
      options: [
        ['They must be consecrated and wash their garments', 
         'They must fast for seven days', 
         'They must offer sacrifices daily', 
         'They must build a new altar'],
        ['They must fast for seven days', 
         'They must offer sacrifices daily', 
         'They must build a new altar', 
         'They must be consecrated and wash their garments'],
        ['They must offer sacrifices daily', 
         'They must build a new altar', 
         'They must be consecrated and wash their garments', 
         'They must fast for seven days'],
        ['They must build a new altar', 
         'They must be consecrated and wash their garments', 
         'They must fast for seven days', 
         'They must offer sacrifices daily']
      ],
      answer: 'They must be consecrated and wash their garments',
      level: 'hard',
      hint: 'Exodus 19:10-11',
    },
    {
      id: 'exodus-hard-12',
      book: 'Exodus',
      chapter: 25,
      question: 'What did God command Moses to build as a place of worship?',
      options: [
        ['The Tabernacle', 
         'The Temple', 
         'An altar', 
         'A synagogue'],
        ['The Temple', 
         'The Tabernacle', 
         'An altar', 
         'A synagogue'],
        ['An altar', 
         'A synagogue', 
         'The Tabernacle', 
         'The Temple'],
        ['A synagogue', 
         'The Temple', 
         'The Tabernacle', 
         'An altar']
      ],
      answer: 'The Tabernacle',
      level: 'hard',
      hint: 'Exodus 25:8-9',
    },
    {
      id: 'exodus-hard-13',
      book: 'Exodus',
      chapter: 32,
      question: 'What specific idol did the Israelites create and worship while Moses was on Mount Sinai?',
      options: [
        ['A golden calf', 
         'A silver serpent', 
         'A bronze bull', 
         'A wooden idol'],
        ['A silver serpent', 
         'A bronze bull', 
         'A wooden idol', 
         'A golden calf'],
        ['A bronze bull', 
         'A wooden idol', 
         'A golden calf', 
         'A silver serpent'],
        ['A wooden idol', 
         'A golden calf', 
         'A silver serpent', 
         'A bronze bull']
      ],
      answer: 'A golden calf',
      level: 'hard',
      hint: 'Exodus 32:4',
    },
    {
      id: 'exodus-hard-14',
      book: 'Exodus',
      chapter: 34,
      question: 'What new name did God give to Moses after the incident with the golden calf?',
      options: [
        ['Jehovah', 
         'El Shaddai', 
         'Yahweh', 
         'Adonai'],
        ['El Shaddai', 
         'Yahweh', 
         'Adonai', 
         'Jehovah'],
        ['Yahweh', 
         'Adonai', 
         'Jehovah', 
         'El Shaddai'],
        ['Adonai', 
         'Jehovah', 
         'El Shaddai', 
         'Yahweh']
      ],
      answer: 'Yahweh',
      level: 'hard',
      hint: 'Exodus 34:5-7',
    },
    {
      id: 'exodus-hard-15',
      book: 'Exodus',
      chapter: 15,
      question: 'What agricultural miracle did God perform for the Israelites in the wilderness?',
      options: [
        ['Provided quail and manna', 
         'Made water come from a rock', 
         'Parted the Red Sea', 
         'Gave them fertile land'],
        ['Parted the Red Sea', 
         'Gave them fertile land', 
         'Made water come from a rock', 
         'Provided quail and manna'],
        ['Made water come from a rock', 
         'Parted the Red Sea', 
         'Provided quail and manna', 
         'Gave them fertile land'],
        ['Gave them fertile land', 
         'Parted the Red Sea', 
         'Provided quail and manna', 
         'Made water come from a rock']
      ],
      answer: 'Provided quail and manna',
      level: 'hard',
      hint: 'Exodus 16:13-14',
    },
    {
      id: 'exodus-hard-16',
      book: 'Exodus',
      chapter: 19,
      question: 'What did God say to Moses about the Israelites in Exodus 19?',
      options: [
        ['They will be His treasured possession', 
         'They will be His servants', 
         'They will be a cursed people', 
         'They will be forgotten'],
        ['They will be His servants', 
         'They will be forgotten', 
         'They will be a cursed people', 
         'They will be His treasured possession'],
        ['They will be a cursed people', 
         'They will be forgotten', 
         'They will be His servants', 
         'They will be His treasured possession'],
        ['They will be forgotten', 
         'They will be His treasured possession', 
         'They will be His servants', 
         'They will be a cursed people']
      ],
      answer: 'They will be His treasured possession',
      level: 'hard',
      hint: 'Exodus 19:5-6',
    },
    {
      id: 'exodus-hard-17',
      book: 'Exodus',
      chapter: 24,
      question: 'What did Moses do with the stone tablets after receiving them from God?',
      options: [
        ['He placed them in the Tabernacle', 
         'He broke them', 
         'He carried them up Mount Sinai', 
         'He gave them to Aaron'],
        ['He broke them', 
         'He carried them up Mount Sinai', 
         'He placed them in the Tabernacle', 
         'He gave them to Aaron'],
        ['He carried them up Mount Sinai', 
         'He broke them', 
         'He gave them to Aaron', 
         'He placed them in the Tabernacle'],
        ['He gave them to Aaron', 
         'He placed them in the Tabernacle', 
         'He broke them', 
         'He carried them up Mount Sinai']
      ],
      answer: 'He placed them in the Tabernacle',
      level: 'hard',
      hint: 'Exodus 24:12-18',
    },
    {
      id: 'exodus-hard-18',
      book: 'Exodus',
      chapter: 40,
      question: 'What cloud covered the Tabernacle, signifying God’s presence?',
      options: [
        ['A thick cloud', 
         'A thin mist', 
         'A storm cloud', 
         'A rainbow'],
        ['A thin mist', 
         'A storm cloud', 
         'A rainbow', 
         'A thick cloud'],
        ['A storm cloud', 
         'A rainbow', 
         'A thick cloud', 
         'A thin mist'],
        ['A rainbow', 
         'A thick cloud', 
         'A thin mist', 
         'A storm cloud']
      ],
      answer: 'A thick cloud',
      level: 'hard',
      hint: 'Exodus 40:34-38',
    },
    {
      id: 'exodus-hard-19',
      book: 'Exodus',
      chapter: 12,
      question: 'What was the purpose of the Passover meal?',
      options: [
        ['To commemorate the Israelites’ deliverance from Egypt', 
         'To celebrate the harvest', 
         'To honor the priests', 
         'To mark the New Year'],
        ['To celebrate the harvest', 
         'To honor the priests', 
         'To mark the New Year', 
         'To commemorate the Israelites’ deliverance from Egypt'],
        ['To honor the priests', 
         'To commemorate the Israelites’ deliverance from Egypt', 
         'To mark the New Year', 
         'To celebrate the harvest'],
        ['To mark the New Year', 
         'To commemorate the Israelites’ deliverance from Egypt', 
         'To celebrate the harvest', 
         'To honor the priests']
      ],
      answer: 'To commemorate the Israelites’ deliverance from Egypt',
      level: 'hard',
      hint: 'Exodus 12:14',
    },
    {
      id: 'exodus-hard-20',
      book: 'Exodus',
      chapter: 19,
      question: 'What did God tell Moses to tell the Israelites regarding consecration before receiving the Law?',
      options: [
        ['They must wash their clothes and abstain from certain activities', 
         'They must fast for seven days', 
         'They must offer sacrifices daily', 
         'They must build an altar'],
        ['They must fast for seven days', 
         'They must offer sacrifices daily', 
         'They must build an altar', 
         'They must wash their clothes and abstain from certain activities'],
        ['They must offer sacrifices daily', 
         'They must build an altar', 
         'They must wash their clothes and abstain from certain activities', 
         'They must fast for seven days'],
        ['They must build an altar', 
         'They must wash their clothes and abstain from certain activities', 
         'They must fast for seven days', 
         'They must offer sacrifices daily']
      ],
      answer: 'They must wash their clothes and abstain from certain activities',
      level: 'hard',
      hint: 'Exodus 19:10-11',
    },
  ];
  
  export default exodus;