const genesis = [
    // Easy questions
    {
      id: 'genesis-easy-1',
      book: 'Genesis',
      chapter: 1,
      question: 'Who was the first human created by God?',
      options: ['Adam', 'Noah', 'Abraham', 'Moses'],
      answer: 'Adam',
      level: 'easy',
      hint: 'Genesis 2:7',
    },
    {
      id: 'genesis-easy-2',
      book: 'Genesis',
      chapter: 1,
      question: 'On which day did God create humans?',
      options: ['Sixth day', 'First day', 'Third day', 'Seventh day'],
      answer: 'Sixth day',
      level: 'easy',
      hint: 'Genesis 1:26-27',
    },
    {
      id: 'genesis-easy-3',
      book: 'Genesis',
      chapter: 1,
      question: 'What was the name of the garden where Adam and Eve lived?',
      options: ['Garden of Eden', 'Garden of Gethsemane', 'Garden of Olives', 'Garden of Babylon'],
      answer: 'Garden of Eden',
      level: 'easy',
      hint: 'Genesis 2:8',
    },
    {
      id: 'genesis-easy-4',
      book: 'Genesis',
      chapter: 2,
      question: 'Who was created from one of Adam’s ribs?',
      options: ['Eve', 'Sarah', 'Hagar', 'Rebekah'],
      answer: 'Eve',
      level: 'easy',
      hint: 'Genesis 2:21-22',
    },
    {
      id: 'genesis-easy-5',
      book: 'Genesis',
      chapter: 3,
      question: 'What fruit did Adam and Eve eat that God had forbidden?',
      options: ['Fruit from the Tree of Knowledge of Good and Evil', 'Apple', 'Fig', 'Pomegranate'],
      answer: 'Fruit from the Tree of Knowledge of Good and Evil',
      level: 'easy',
      hint: 'Genesis 3:6',
    },
    {
      id: 'genesis-easy-6',
      book: 'Genesis',
      chapter: 4,
      question: 'Who was the first murderer according to Genesis?',
      options: ['Cain', 'Abel', 'Seth', 'Enosh'],
      answer: 'Cain',
      level: 'easy',
      hint: 'Genesis 4:8',
    },
    {
      id: 'genesis-easy-7',
      book: 'Genesis',
      chapter: 5,
      question: 'Who was the father of Noah?',
      options: ['Lamech', 'Methuselah', 'Enoch', 'Jared'],
      answer: 'Lamech',
      level: 'easy',
      hint: 'Genesis 5:28-29',
    },
    {
      id: 'genesis-easy-8',
      book: 'Genesis',
      chapter: 6,
      question: 'What was the reason for God’s decision to flood the earth?',
      options: ['Wickedness of humanity', 'Lack of food', 'Natural disaster', 'War'],
      answer: 'Wickedness of humanity',
      level: 'easy',
      hint: 'Genesis 6:5',
    },
    {
      id: 'genesis-easy-9',
      book: 'Genesis',
      chapter: 7,
      question: 'How many of each clean animal did Noah take into the ark?',
      options: ['Seven pairs', 'One pair', 'Five pairs', 'Two pairs'],
      answer: 'Seven pairs',
      level: 'easy',
      hint: 'Genesis 7:2',
    },
    {
      id: 'genesis-easy-10',
      book: 'Genesis',
      chapter: 9,
      question: 'What symbol did God set in the sky as a promise never to flood the earth again?',
      options: ['Rainbow', 'Star', 'Cloud', 'Sun'],
      answer: 'Rainbow',
      level: 'easy',
      hint: 'Genesis 9:13',
    },
  
    // Medium questions
    {
      id: 'genesis-medium-1',
      book: 'Genesis',
      chapter: 11,
      question: 'What was the name of the tower that people built to reach the heavens?',
      options: ['Tower of Babel', 'Tower of David', 'Tower of Jerusalem', 'Tower of Siloam'],
      answer: 'Tower of Babel',
      level: 'medium',
      hint: 'Genesis 11:4',
    },
    {
      id: 'genesis-medium-2',
      book: 'Genesis',
      chapter: 12,
      question: 'Which patriarch did God call to leave his country and family?',
      options: ['Abraham', 'Isaac', 'Jacob', 'Joseph'],
      answer: 'Abraham',
      level: 'medium',
      hint: 'Genesis 12:1',
    },
    {
      id: 'genesis-medium-3',
      book: 'Genesis',
      chapter: 13,
      question: 'What dispute caused Abram and Lot to separate?',
      options: ['Pastoral conflicts', 'Inheritance issues', 'Religious differences', 'Political alliances'],
      answer: 'Pastoral conflicts',
      level: 'medium',
      hint: 'Genesis 13:5-7',
    },
    {
      id: 'genesis-medium-4',
      book: 'Genesis',
      chapter: 16,
      question: 'Who was Hagar in relation to Abram and Sarai?',
      options: ['Sarai’s Egyptian maidservant', 'Abram’s sister', 'Sarai’s mother', 'A foreign queen'],
      answer: 'Sarai’s Egyptian maidservant',
      level: 'medium',
      hint: 'Genesis 16:1',
    },
    {
      id: 'genesis-medium-5',
      book: 'Genesis',
      chapter: 18,
      question: 'Which city did God reveal to Abraham would be the future of his descendants?',
      options: ['Sodom', 'Jericho', 'Hebron', 'Shiloh'],
      answer: 'Sodom',
      level: 'medium',
      hint: 'Genesis 18:20-21',
    },
    {
      id: 'genesis-medium-6',
      book: 'Genesis',
      chapter: 22,
      question: 'What test did God give to Abraham in Genesis 22?',
      options: ['To sacrifice his son Isaac', 'To build an altar', 'To move to Canaan', 'To trade with foreigners'],
      answer: 'To sacrifice his son Isaac',
      level: 'medium',
      hint: 'Genesis 22:2',
    },
    {
      id: 'genesis-medium-7',
      book: 'Genesis',
      chapter: 25,
      question: 'Who was Isaac’s twin brother?',
      options: ['Esau', 'Jacob', 'Abel', 'Seth'],
      answer: 'Esau',
      level: 'medium',
      hint: 'Genesis 25:25',
    },
    {
      id: 'genesis-medium-8',
      book: 'Genesis',
      chapter: 27,
      question: 'Who tricked Isaac into giving Jacob the blessing meant for Esau?',
      options: ['Rebekah', 'Rachel', 'Leah', 'Dinah'],
      answer: 'Rebekah',
      level: 'medium',
      hint: 'Genesis 27:18-29',
    },
    {
      id: 'genesis-medium-9',
      book: 'Genesis',
      chapter: 37,
      question: 'What did Joseph’s brothers sell him for?',
      options: ['Twenty pieces of silver', 'A slave girl', 'A cow', 'A donkey'],
      answer: 'Twenty pieces of silver',
      level: 'medium',
      hint: 'Genesis 37:28',
    },
    {
      id: 'genesis-medium-10',
      book: 'Genesis',
      chapter: 50,
      question: 'What did Joseph say to his brothers when he revealed his identity?',
      options: ['“You meant evil against me, but God meant it for good”', '“I seek revenge”', '“Leave me alone”', '“Why did you do this to me?”'],
      answer: '“You meant evil against me, but God meant it for good”',
      level: 'medium',
      hint: 'Genesis 50:20',
    },
  
    // Hard questions
    {
      id: 'genesis-hard-1',
      book: 'Genesis',
      chapter: 5,
      question: 'How long did Methuselah live, making him the longest-lived human according to Genesis?',
      options: ['969 years', '120 years', '930 years', '777 years'],
      answer: '969 years',
      level: 'hard',
      hint: 'Genesis 5:27',
    },
    {
      id: 'genesis-hard-2',
      book: 'Genesis',
      chapter: 6,
      question: 'Who were the "sons of God" that took human wives, leading to the corruption of mankind?',
      options: [
        ['Angelic beings', 'Descendants of Seth', 'Descendants of Cain', 'Ancient kings'],
        ['Descendants of Seth', 'Angelic beings', 'Descendants of Cain', 'Ancient kings'],
        ['Descendants of Cain', 'Ancient kings', 'Angelic beings', 'Descendants of Seth'],
        ['Ancient kings', 'Descendants of Seth', 'Descendants of Cain', 'Angelic beings'],
      ],
      answer: 'Angelic beings',
      level: 'hard',
      hint: 'Genesis 6:2',
    },
    {
      id: 'genesis-hard-3',
      book: 'Genesis',
      chapter: 12,
      question: 'What was the original name of the land God promised to Abraham?',
      options: [
        ['Canaan', 'Egypt', 'Ur of the Chaldeans', 'Haran'],
        ['Ur of the Chaldeans', 'Canaan', 'Egypt', 'Haran'],
        ['Haran', 'Egypt', 'Canaan', 'Ur of the Chaldeans'],
        ['Egypt', 'Ur of the Chaldeans', 'Haran', 'Canaan'],
      ],
      answer: 'Ur of the Chaldeans',
      level: 'hard',
      hint: 'Genesis 12:1',
    },
    {
      id: 'genesis-hard-4',
      book: 'Genesis',
      chapter: 15,
      question: 'What specific promise did God make to Abram in Genesis 15?',
      options: [
        ['He would have a son and numerous descendants', 'He would become king of Egypt', 'He would conquer Canaan', 'He would build a great city'],
        ['He would build a great city', 'He would conquer Canaan', 'He would become king of Egypt', 'He would have a son and numerous descendants'],
        ['He would conquer Canaan', 'He would have a son and numerous descendants', 'He would become king of Egypt', 'He would build a great city'],
        ['He would become king of Egypt', 'He would build a great city', 'He would have a son and numerous descendants', 'He would conquer Canaan'],
      ],
      answer: 'He would have a son and numerous descendants',
      level: 'hard',
      hint: 'Genesis 15:5-6',
    },
    {
      id: 'genesis-hard-5',
      book: 'Genesis',
      chapter: 22,
      question: 'What did Abraham name the place where he almost sacrificed Isaac?',
      options: [
        ['The LORD Will Provide', 'Mount Sinai', 'Beersheba', 'Bethel'],
        ['Mount Sinai', 'Beersheba', 'The LORD Will Provide', 'Bethel'],
        ['Bethel', 'Mount Sinai', 'The LORD Will Provide', 'Beersheba'],
        ['Beersheba', 'Bethel', 'Mount Sinai', 'The LORD Will Provide'],
      ],
      answer: 'The LORD Will Provide',
      level: 'hard',
      hint: 'Genesis 22:14',
    },
    {
      id: 'genesis-hard-6',
      book: 'Genesis',
      chapter: 25,
      question: 'Who was the wife of Esau?',
      options: [
        ['Judith and Basemath', 'Rebekah and Leah', 'Rachel and Bilhah', 'Dinah and Tamar'],
        ['Rebekah and Leah', 'Judith and Basemath', 'Rachel and Bilhah', 'Dinah and Tamar'],
        ['Rachel and Bilhah', 'Rebekah and Leah', 'Judith and Basemath', 'Dinah and Tamar'],
        ['Dinah and Tamar', 'Rachel and Bilhah', 'Rebekah and Leah', 'Judith and Basemath'],
      ],
      answer: 'Judith and Basemath',
      level: 'hard',
      hint: 'Genesis 26:34',
    },
    {
      id: 'genesis-hard-7',
      book: 'Genesis',
      chapter: 28,
      question: 'What did Jacob see in his dream at Bethel?',
      options: [
        ['A ladder reaching to heaven with angels ascending and descending', 'A burning bush', 'An angel with a sword', 'A tree with fruit'],
        ['A burning bush', 'A ladder reaching to heaven with angels ascending and descending', 'An angel with a sword', 'A tree with fruit'],
        ['An angel with a sword', 'A burning bush', 'A ladder reaching to heaven with angels ascending and descending', 'A tree with fruit'],
        ['A tree with fruit', 'An angel with a sword', 'A burning bush', 'A ladder reaching to heaven with angels ascending and descending'],
      ],
      answer: 'A ladder reaching to heaven with angels ascending and descending',
      level: 'hard',
      hint: 'Genesis 28:12',
    },
    {
      id: 'genesis-hard-8',
      book: 'Genesis',
      chapter: 32,
      question: 'What was the name of the place where Jacob wrestled with the angel?',
      options: [
        ['Peniel', 'Bethel', 'Shechem', 'Hebron'],
        ['Bethel', 'Peniel', 'Shechem', 'Hebron'],
        ['Shechem', 'Hebron', 'Peniel', 'Bethel'],
        ['Hebron', 'Shechem', 'Bethel', 'Peniel'],
      ],
      answer: 'Peniel',
      level: 'hard',
      hint: 'Genesis 32:30',
    },
    {
      id: 'genesis-hard-9',
      book: 'Genesis',
      chapter: 37,
      question: 'Which of Jacob’s sons was sold into slavery?',
      options: [
        ['Joseph', 'Reuben', 'Simeon', 'Levi'],
        ['Reuben', 'Joseph', 'Simeon', 'Levi'],
        ['Simeon', 'Levi', 'Joseph', 'Reuben'],
        ['Levi', 'Simeon', 'Reuben', 'Joseph'],
      ],
      answer: 'Joseph',
      level: 'hard',
      hint: 'Genesis 37:28',
    },
    {
      id: 'genesis-hard-10',
      book: 'Genesis',
      chapter: 45,
      question: 'What position did Pharaoh appoint Joseph to in Egypt?',
      options: [
        ['Governor over Egypt', 'Priest of the temple', 'Commander of the army', 'Advisor to the king'],
        ['Priest of the temple', 'Governor over Egypt', 'Commander of the army', 'Advisor to the king'],
        ['Commander of the army', 'Governor over Egypt', 'Priest of the temple', 'Advisor to the king'],
        ['Advisor to the king', 'Governor over Egypt', 'Priest of the temple', 'Commander of the army'],
      ],
      answer: 'Governor over Egypt',
      level: 'hard',
      hint: 'Genesis 41:41-43',
    },
  
    // Hard questions
    {
      id: 'genesis-hard-11',
      book: 'Genesis',
      chapter: 3,
      question: 'What punishment did God give to the serpent after the fall?',
      options: [
        ['Crawling on its belly and eating dust', 'Being cast out of Eden', 'No punishment', 'Having wings'],
        ['Crawling on its belly and eating dust', 'Being cast out of Eden', 'No punishment', 'Having wings'],
        ['Having wings', 'Crawling on its belly and eating dust', 'Being cast out of Eden', 'No punishment'],
        ['Being cast out of Eden', 'Having wings', 'Crawling on its belly and eating dust', 'No punishment'],
      ],
      answer: 'Crawling on its belly and eating dust',
      level: 'hard',
      hint: 'Genesis 3:14',
    },
    {
      id: 'genesis-hard-12',
      book: 'Genesis',
      chapter: 4,
      question: 'What was the profession of Cain and Abel?',
      options: [
        ['Cain was a farmer and Abel was a shepherd', 'Cain was a shepherd and Abel was a farmer', 'Both were shepherds', 'Both were farmers'],
        ['Cain was a shepherd and Abel was a farmer', 'Cain was a farmer and Abel was a shepherd', 'Both were shepherds', 'Both were farmers'],
        ['Both were shepherds', 'Both were farmers', 'Cain was a farmer and Abel was a shepherd', 'Cain was a shepherd and Abel was a farmer'],
        ['Cain was a farmer and Abel was a shepherd', 'Cain was a shepherd and Abel was a farmer', 'Both were farmers', 'Both were shepherds'],
      ],
      answer: 'Cain was a farmer and Abel was a shepherd',
      level: 'hard',
      hint: 'Genesis 4:2',
    },
    {
      id: 'genesis-hard-13',
      book: 'Genesis',
      chapter: 6,
      question: 'Who was Lamech and what was unique about his declaration?',
      options: [
        ['A descendant of Cain who spoke of vengeance', 'Noah’s father who built the ark', 'A priest who offered sacrifices', 'Abraham’s servant who guided him'],
        ['Noah’s father who built the ark', 'A descendant of Cain who spoke of vengeance', 'A priest who offered sacrifices', 'Abraham’s servant who guided him'],
        ['A priest who offered sacrifices', 'Abraham’s servant who guided him', 'A descendant of Cain who spoke of vengeance', 'Noah’s father who built the ark'],
        ['Abraham’s servant who guided him', 'A descendant of Cain who spoke of vengeance', 'Noah’s father who built the ark', 'A priest who offered sacrifices'],
      ],
      answer: 'A descendant of Cain who spoke of vengeance',
      level: 'hard',
      hint: 'Genesis 4:19-24',
    },
    {
      id: 'genesis-hard-14',
      book: 'Genesis',
      chapter: 11,
      question: 'What was the reason God confused the language of the people at Babel?',
      options: [
        ['To prevent them from completing the tower', 'To punish them for idolatry', 'To scatter them across the earth', 'To create diversity'],
        ['To prevent them from completing the tower', 'To punish them for idolatry', 'To scatter them across the earth', 'To create diversity'],
        ['To scatter them across the earth', 'To prevent them from completing the tower', 'To punish them for idolatry', 'To create diversity'],
        ['To create diversity', 'To scatter them across the earth', 'To prevent them from completing the tower', 'To punish them for idolatry'],
      ],
      answer: 'To prevent them from completing the tower',
      level: 'hard',
      hint: 'Genesis 11:7',
    },
    {
      id: 'genesis-hard-15',
      book: 'Genesis',
      chapter: 22,
      question: 'What was the name of the mountain where Abraham was to sacrifice Isaac?',
      options: [
        ['Mount Moriah', 'Mount Sinai', 'Mount Horeb', 'Mount Zion'],
        ['Mount Sinai', 'Mount Horeb', 'Mount Zion', 'Mount Moriah'],
        ['Mount Horeb', 'Mount Zion', 'Mount Moriah', 'Mount Sinai'],
        ['Mount Zion', 'Mount Moriah', 'Mount Sinai', 'Mount Horeb'],
      ],
      answer: 'Mount Moriah',
      level: 'hard',
      hint: 'Genesis 22:2',
    },
    {
      id: 'genesis-hard-16',
      book: 'Genesis',
      chapter: 28,
      question: 'What did Jacob name the stone he set up after his dream?',
      options: [
        ['Bethel', 'Shechem', 'Hebron', 'Bethel'],
        ['Shechem', 'Hebron', 'Bethel', 'Bethel'],
        ['Hebron', 'Bethel', 'Shechem', 'Bethel'],
        ['Bethel', 'Shechem', 'Hebron', 'Bethel'],
      ],
      answer: 'Bethel',
      level: 'hard',
      hint: 'Genesis 28:19',
    },
    {
      id: 'genesis-hard-17',
      book: 'Genesis',
      chapter: 32,
      question: 'What injury did Jacob sustain during his wrestling with the angel?',
      options: [
        ['He had his hip socket touched', 'He was cut on his arm', 'He broke his leg', 'He was blind'],
        ['He broke his leg', 'He was cut on his arm', 'He had his hip socket touched', 'He was blind'],
        ['He was blind', 'He had his hip socket touched', 'He broke his leg', 'He was cut on his arm'],
        ['He was cut on his arm', 'He broke his leg', 'He was blind', 'He had his hip socket touched'],
      ],
      answer: 'He had his hip socket touched',
      level: 'hard',
      hint: 'Genesis 32:32',
    },
    {
      id: 'genesis-hard-18',
      book: 'Genesis',
      chapter: 37,
      question: 'What dream did Joseph have that caused his brothers to envy him?',
      options: [
        ['Sheaves of grain bowing to his sheaf', 'He was a great leader', 'Stars bowed to him', 'He built a great house'],
        ['He built a great house', 'He was a great leader', 'Stars bowed to him', 'Sheaves of grain bowing to his sheaf'],
        ['Stars bowed to him', 'He was a great leader', 'He built a great house', 'Sheaves of grain bowing to his sheaf'],
        ['He was a great leader', 'Stars bowed to him', 'Sheaves of grain bowing to his sheaf', 'He built a great house'],
      ],
      answer: 'Sheaves of grain bowing to his sheaf',
      level: 'hard',
      hint: 'Genesis 37:7-11',
    },
    {
      id: 'genesis-hard-19',
      book: 'Genesis',
      chapter: 45,
      question: 'How did Joseph verify his identity to his brothers?',
      options: [
        ['He showed them his silver cup', 'He revealed his dreams', 'He performed miracles', 'He provided detailed accounts of their past'],
        ['He performed miracles', 'He showed them his silver cup', 'He revealed his dreams', 'He provided detailed accounts of their past'],
        ['He revealed his dreams', 'He provided detailed accounts of their past', 'He showed them his silver cup', 'He performed miracles'],
        ['He provided detailed accounts of their past', 'He revealed his dreams', 'He performed miracles', 'He showed them his silver cup'],
      ],
      answer: 'He showed them his silver cup',
      level: 'hard',
      hint: 'Genesis 45:1-11',
    },
    {
      id: 'genesis-hard-20',
      book: 'Genesis',
      chapter: 50,
      question: 'What instruction did Joseph give his brothers regarding their burial?',
      options: [
        ['To bury him with their father in Canaan', 'To bury him in Egypt', 'To build a tomb for him', 'To scatter his ashes'],
        ['To bury him in Egypt', 'To build a tomb for him', 'To scatter his ashes', 'To bury him with their father in Canaan'],
        ['To build a tomb for him', 'To scatter his ashes', 'To bury him with their father in Canaan', 'To bury him in Egypt'],
        ['To scatter his ashes', 'To bury him with their father in Canaan', 'To bury him in Egypt', 'To build a tomb for him'],
      ],
      answer: 'To bury him with their father in Canaan',
      level: 'hard',
      hint: 'Genesis 50:24-25',
    },
  ];
  
  export default genesis;